# Generated by Django 5.2.15 on 2026-07-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_collegeuser_professoruser_ituserrole"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminuser",
            name="account_status",
            field=models.CharField(
                choices=[
                    ("pending_verification", "Pending Verification"),
                    ("active", "Active"),
                    ("suspended", "Suspended"),
                    ("deactivated", "Deactivated"),
                ],
                db_index=True,
                default="active",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="adminuser",
            name="failed_login_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="adminuser",
            name="locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="collegeuser",
            name="account_status",
            field=models.CharField(
                choices=[
                    ("pending_verification", "Pending Verification"),
                    ("active", "Active"),
                    ("suspended", "Suspended"),
                    ("deactivated", "Deactivated"),
                ],
                db_index=True,
                default="active",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="collegeuser",
            name="failed_login_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="collegeuser",
            name="locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facultyuser",
            name="account_status",
            field=models.CharField(
                choices=[
                    ("pending_verification", "Pending Verification"),
                    ("active", "Active"),
                    ("suspended", "Suspended"),
                    ("deactivated", "Deactivated"),
                ],
                db_index=True,
                default="active",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="facultyuser",
            name="failed_login_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="facultyuser",
            name="locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ituser",
            name="account_status",
            field=models.CharField(
                choices=[
                    ("pending_verification", "Pending Verification"),
                    ("active", "Active"),
                    ("suspended", "Suspended"),
                    ("deactivated", "Deactivated"),
                ],
                db_index=True,
                default="active",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="ituser",
            name="failed_login_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ituser",
            name="locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="professoruser",
            name="account_status",
            field=models.CharField(
                choices=[
                    ("pending_verification", "Pending Verification"),
                    ("active", "Active"),
                    ("suspended", "Suspended"),
                    ("deactivated", "Deactivated"),
                ],
                db_index=True,
                default="active",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="professoruser",
            name="failed_login_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="professoruser",
            name="locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
