services:
  web:
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - media_data:/app/media
      - static_data:/app/staticfiles
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.development
      DEBUG: "True"

  celery_worker:
    volumes:
      - .:/app
      - media_data:/app/media
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.development
      DEBUG: "True"

  celery_beat:
    volumes:
      - .:/app
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.development
      DEBUG: "True"

  # Expose database and Redis ports ONLY during local development for local GUI tools / debugging
  db:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"
