# Generated by Django 5.2.15 on 2026-07-02 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        ("it_recruitment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="companymember",
            name="recruiter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_memberships",
                to="it_recruitment.recruiterprofile",
            ),
        ),
        migrations.AddConstraint(
            model_name="companymember",
            constraint=models.UniqueConstraint(
                fields=("company", "recruiter"), name="unique_company_recruiter"
            ),
        ),
    ]
