# Generated by Django 5.2.15 on 2026-07-02 22:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0002_initial"),
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyLocation",
            fields=[
                (
                    "created_by_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("label", models.CharField(blank=True, max_length=120)),
                ("address_line", models.CharField(blank=True, max_length=300)),
                ("city", models.CharField(blank=True, max_length=120)),
                ("state", models.CharField(blank=True, max_length=120)),
                ("country", models.CharField(blank=True, max_length=120)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("is_headquarters", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "it_company_location",
            },
        ),
        migrations.AddField(
            model_name="company",
            name="address_line",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="company",
            name="benefits",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="company",
            name="city",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="company",
            name="country",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="company",
            name="cover_banner_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="company_banners",
                to="documents.storedfile",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="culture",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="company",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="company",
            name="facebook_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="company",
            name="founded_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="gst_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="company",
            name="instagram_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="company",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="company",
            name="legal_name",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="company",
            name="linkedin_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="company",
            name="mission",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="company",
            name="organization_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("private_limited", "Private Limited"),
                    ("public_limited", "Public Limited"),
                    ("startup", "Startup"),
                    ("mnc", "MNC"),
                    ("government", "Government"),
                    ("ngo", "NGO / Non-Profit"),
                    ("partnership", "Partnership"),
                    ("proprietorship", "Proprietorship"),
                    ("llp", "LLP"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="company",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="company",
            name="state",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="company",
            name="twitter_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="company",
            name="verification_remarks",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="company",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="verified_by_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="vision",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="company",
            name="youtube_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="company_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1-10", "1-10 employees"),
                    ("11-50", "11-50 employees"),
                    ("51-200", "51-200 employees"),
                    ("201-500", "201-500 employees"),
                    ("501-1000", "501-1000 employees"),
                    ("1001-5000", "1001-5000 employees"),
                    ("5000+", "5000+ employees"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                    ("suspended", "Suspended"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="companymember",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("admin", "Admin"),
                    ("recruiter", "Recruiter"),
                ],
                default="recruiter",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(
                fields=["verification_status", "is_active"],
                name="it_company_verific_037ee1_idx",
            ),
        ),
        migrations.AddField(
            model_name="companylocation",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="companies.company",
            ),
        ),
    ]
