# Generated by Django 5.2.15 on 2026-07-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0003_companylocation_company_address_line_and_more"),
        ("it_recruitment", "0003_alter_jobseekerprofile_managers_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="companymember",
            index=models.Index(
                fields=["is_active", "is_deleted"],
                name="it_company__is_acti_e3e6db_idx",
            ),
        ),
    ]
