# Generated by Django 5.2.15 on 2026-07-06 18:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0004_production_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="company",
            name="it_company_verific_037ee1_idx",
        ),
        migrations.RemoveField(
            model_name="company",
            name="verification_remarks",
        ),
        migrations.RemoveField(
            model_name="company",
            name="verification_status",
        ),
        migrations.RemoveField(
            model_name="company",
            name="verified_at",
        ),
        migrations.RemoveField(
            model_name="company",
            name="verified_by_id",
        ),
    ]
