# Generated by Django 5.2.15 on 2026-07-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_remove_company_it_company_verific_037ee1_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='is_active',
        ),
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('deactivated', 'Deactivated'), ('suspended', 'Suspended'), ('blocked', 'Blocked')], db_index=True, default='active', max_length=20),
        ),
    ]
