# Generated by Django 5.2.15 on 2026-07-17 10:38

import apps.core.validators.common
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_remove_company_status_company_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='benefits',
            field=models.TextField(blank=True, validators=[apps.core.validators.common.validate_clean_text]),
        ),
        migrations.AlterField(
            model_name='company',
            name='culture',
            field=models.TextField(blank=True, validators=[apps.core.validators.common.validate_clean_text]),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, validators=[apps.core.validators.common.validate_clean_text]),
        ),
        migrations.AlterField(
            model_name='company',
            name='founded_year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800)]),
        ),
        migrations.AlterField(
            model_name='company',
            name='gst_number',
            field=models.CharField(blank=True, max_length=20, validators=[apps.core.validators.common.validate_gst]),
        ),
        migrations.AlterField(
            model_name='company',
            name='legal_name',
            field=models.CharField(blank=True, max_length=300, validators=[apps.core.validators.common.validate_organization_name]),
        ),
        migrations.AlterField(
            model_name='company',
            name='mission',
            field=models.TextField(blank=True, validators=[apps.core.validators.common.validate_clean_text]),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=300, validators=[apps.core.validators.common.validate_organization_name]),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[apps.core.validators.common.validate_phone]),
        ),
        migrations.AlterField(
            model_name='company',
            name='vision',
            field=models.TextField(blank=True, validators=[apps.core.validators.common.validate_clean_text]),
        ),
    ]
