# Generated by Django 5.2.15 on 2026-07-02 19:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeeSchedule",
            fields=[
                (
                    "created_by_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("it", "IT Recruitment"),
                            ("faculty", "Faculty Recruitment"),
                            ("platform", "Platform"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "fee_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage"),
                            ("fixed", "Fixed Amount"),
                        ],
                        default="percentage",
                        max_length=20,
                    ),
                ),
                (
                    "percentage_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "fixed_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("currency", models.CharField(default="INR", max_length=3)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "effective_from",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("effective_until", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "db_table": "billing_fee_schedule",
            },
        ),
        migrations.CreateModel(
            name="PlacementFee",
            fields=[
                (
                    "created_by_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("it", "IT Recruitment"),
                            ("faculty", "Faculty Recruitment"),
                            ("platform", "Platform"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("it_job_application", "IT Job Application"),
                            ("faculty_application", "Faculty Application"),
                            ("it_job_posting", "IT Job Posting"),
                            ("faculty_vacancy", "Faculty Vacancy"),
                            ("it_company", "IT Company"),
                            ("faculty_college", "Faculty College"),
                            ("stored_file", "Stored File"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("entity_id", models.UUIDField(db_index=True)),
                (
                    "base_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "calculated_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("currency", models.CharField(default="INR", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("invoiced", "Invoiced"),
                            ("waived", "Waived"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "bill_to_entity_type",
                    models.CharField(
                        choices=[
                            ("it_job_application", "IT Job Application"),
                            ("faculty_application", "Faculty Application"),
                            ("it_job_posting", "IT Job Posting"),
                            ("faculty_vacancy", "Faculty Vacancy"),
                            ("it_company", "IT Company"),
                            ("faculty_college", "Faculty College"),
                            ("stored_file", "Stored File"),
                        ],
                        max_length=40,
                    ),
                ),
                ("bill_to_entity_id", models.UUIDField(db_index=True)),
                ("bill_to_name_snapshot", models.CharField(max_length=300)),
                ("entity_title_snapshot", models.CharField(blank=True, max_length=300)),
                (
                    "fee_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="placement_fees",
                        to="billing.feeschedule",
                    ),
                ),
            ],
            options={
                "db_table": "billing_placement_fee",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_deleted", False)),
                        fields=("domain", "entity_type", "entity_id"),
                        name="unique_active_placement_fee",
                    )
                ],
            },
        ),
    ]
