# Generated by Django 5.2.15 on 2026-07-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0002_billing_enterprise"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feeschedule",
            name="scope_type",
            field=models.CharField(
                choices=[
                    ("global", "Global"),
                    ("company", "Company"),
                    ("college", "College"),
                    ("role", "Role"),
                    ("designation", "Designation"),
                    ("recruiter", "Recruiter"),
                ],
                db_index=True,
                default="global",
                max_length=20,
            ),
        ),
    ]
