# Generated by Django 5.2.15 on 2026-07-02 20:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_auth_security_fields"),
        ("documents", "0001_initial"),
        ("it_recruitment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobSeekerEducation",
            fields=[
                (
                    "created_by_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("institution", models.CharField(max_length=300)),
                ("degree", models.CharField(max_length=200)),
                ("field_of_study", models.CharField(blank=True, max_length=200)),
                ("start_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("end_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("grade", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "db_table": "it_job_seeker_education",
                "ordering": ["-end_year", "-start_year"],
            },
        ),
        migrations.CreateModel(
            name="JobSeekerExperience",
            fields=[
                (
                    "created_by_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("company_name", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=200)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "db_table": "it_job_seeker_experience",
                "ordering": ["-start_date", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="current_company",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="current_salary",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="employment_type_preference",
            field=models.CharField(
                blank=True,
                choices=[
                    ("full_time", "Full Time"),
                    ("part_time", "Part Time"),
                    ("contract", "Contract"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="github_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="languages",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="linkedin_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="notice_period_days",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="portfolio_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="preferred_location",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="profile_photo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="job_seeker_photos",
                to="documents.storedfile",
            ),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="profile_status",
            field=models.CharField(
                choices=[("active", "Active"), ("deactivated", "Deactivated")],
                db_index=True,
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="profile_visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("private", "Private"),
                    ("employers_only", "Employers Only"),
                ],
                db_index=True,
                default="private",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="recruiterprofile",
            name="company_association",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="recruiterprofile",
            name="department",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="recruiterprofile",
            name="official_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="recruiterprofile",
            name="profile_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recruiter_photos",
                to="documents.storedfile",
            ),
        ),
        migrations.AddField(
            model_name="recruiterprofile",
            name="profile_status",
            field=models.CharField(
                choices=[("active", "Active"), ("deactivated", "Deactivated")],
                db_index=True,
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="recruiterprofile",
            name="profile_visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("private", "Private"),
                    ("employers_only", "Employers Only"),
                ],
                db_index=True,
                default="private",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="recruiterprofile",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("flagged", "Flagged"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="jobseekerprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("profile_completeness__gte", 0), ("profile_completeness__lte", 100)
                ),
                name="job_seeker_profile_completeness_range",
            ),
        ),
        migrations.AddField(
            model_name="jobseekereducation",
            name="job_seeker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="education",
                to="it_recruitment.jobseekerprofile",
            ),
        ),
        migrations.AddField(
            model_name="jobseekerexperience",
            name="job_seeker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="experiences",
                to="it_recruitment.jobseekerprofile",
            ),
        ),
    ]
