# Generated by Django 5.2.15 on 2026-07-03 06:38

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("it_recruitment", "0002_jobseekereducation_jobseekerexperience_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="jobseekerprofile",
            managers=[
                ("profiles", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="recruiterprofile",
            managers=[
                ("profiles", django.db.models.manager.Manager()),
            ],
        ),
    ]
