# Generated by Django 5.2.15 on 2026-07-04 08:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("it_recruitment", "0005_jobseeker_profile_module"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobseekercertification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="jobseekercertification",
            name="created_by_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="jobseekercertification",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="jobseekerexperience",
            name="employment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("full_time", "Full Time"),
                    ("part_time", "Part Time"),
                    ("contract", "Contract"),
                    ("internship", "Internship"),
                    ("temporary", "Temporary"),
                    ("freelance", "Freelance"),
                ],
                default="full_time",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("non_binary", "Non-binary"),
                    ("prefer_not_to_say", "Prefer not to say"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="work_mode_preference",
            field=models.CharField(
                blank=True,
                choices=[
                    ("remote", "Remote"),
                    ("hybrid", "Hybrid"),
                    ("onsite", "On-site"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="jobseekerproject",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="jobseekerproject",
            name="created_by_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="jobseekerproject",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
