# Generated by Django 5.2.15 on 2026-07-04 09:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("it_recruitment", "0007_jobseeker_education_levels"),
        ("jobs", "0003_production_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobSeekerRecommendationSnapshot",
            fields=[
                (
                    "created_by_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("total_matches", models.PositiveIntegerField(default=0)),
                ("new_matches_count", models.PositiveIntegerField(default=0)),
                ("top_match_score", models.PositiveSmallIntegerField(default=0)),
                (
                    "profile_fingerprint",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("computed_at", models.DateTimeField(blank=True, null=True)),
                ("last_notified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "job_seeker",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_snapshot",
                        to="it_recruitment.jobseekerprofile",
                    ),
                ),
                (
                    "top_match_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="jobs.jobposting",
                    ),
                ),
            ],
            options={
                "db_table": "it_job_seeker_recommendation_snapshot",
            },
        ),
        migrations.CreateModel(
            name="JobSeekerJobRecommendation",
            fields=[
                (
                    "created_by_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("match_score", models.PositiveSmallIntegerField()),
                ("score_breakdown", models.JSONField(blank=True, default=dict)),
                ("rank", models.PositiveIntegerField(default=0)),
                ("profile_fingerprint", models.CharField(blank=True, max_length=64)),
                ("computed_at", models.DateTimeField()),
                ("is_new", models.BooleanField(default=False)),
                (
                    "job_posting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seeker_recommendations",
                        to="jobs.jobposting",
                    ),
                ),
                (
                    "job_seeker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_recommendations",
                        to="it_recruitment.jobseekerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "it_job_seeker_job_recommendation",
                "ordering": ["rank"],
                "indexes": [
                    models.Index(
                        fields=["job_seeker", "rank"],
                        name="it_job_seek_job_see_587197_idx",
                    ),
                    models.Index(
                        fields=["job_seeker", "-match_score"],
                        name="it_job_seek_job_see_e464bf_idx",
                    ),
                    models.Index(
                        fields=["job_posting"], name="it_job_seek_job_pos_15b0f9_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("job_seeker", "job_posting"),
                        name="uniq_seeker_job_recommendation",
                    )
                ],
            },
        ),
    ]
