# Generated by Django 5.2.15 on 2026-07-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("it_recruitment", "0010_job_seeker_account_settings"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="jobseekercertification",
            new_name="it_job_seek_job_see_6ad116_idx",
            old_name="it_cert_seeker_cat_idx",
        ),
        migrations.RenameIndex(
            model_name="jobseekercertification",
            new_name="it_job_seek_expiry__82d6ab_idx",
            old_name="it_cert_expiry_idx",
        ),
        migrations.AlterField(
            model_name="jobseekeraccountsettings",
            name="created_by_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
