# Generated by Django 5.2.15 on 2026-07-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("it_recruitment", "0012_recruiter_account_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruiteraccountsettings",
            name="created_by_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
