# Generated by Django 5.2.15 on 2026-07-06 18:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("it_recruitment", "0013_alter_recruiteraccountsettings_created_by_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobseekerprofile",
            name="moderation_status",
        ),
        migrations.RemoveField(
            model_name="recruiterprofile",
            name="moderation_status",
        ),
        migrations.RemoveField(
            model_name="recruiterprofile",
            name="verification_status",
        ),
    ]
