# Generated by Django 5.2.15 on 2026-07-17 10:38

import apps.core.validators.common
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_recruitment', '0014_remove_jobseekerprofile_moderation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='current_company',
            field=models.CharField(blank=True, max_length=200, validators=[apps.core.validators.common.validate_organization_name]),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='current_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='expected_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='experience_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='first_name',
            field=models.CharField(max_length=100, validators=[apps.core.validators.common.validate_clean_text]),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='headline',
            field=models.CharField(blank=True, max_length=300, validators=[apps.core.validators.common.validate_clean_text]),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='last_name',
            field=models.CharField(max_length=100, validators=[apps.core.validators.common.validate_clean_text]),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='notice_period_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[apps.core.validators.common.validate_phone]),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='summary',
            field=models.TextField(blank=True, validators=[apps.core.validators.common.validate_clean_text]),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='company_association',
            field=models.CharField(blank=True, max_length=300, validators=[apps.core.validators.common.validate_organization_name]),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='department',
            field=models.CharField(blank=True, max_length=150, validators=[apps.core.validators.common.validate_clean_text]),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='designation',
            field=models.CharField(blank=True, max_length=150, validators=[apps.core.validators.common.validate_clean_text]),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='first_name',
            field=models.CharField(max_length=100, validators=[apps.core.validators.common.validate_clean_text]),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='last_name',
            field=models.CharField(max_length=100, validators=[apps.core.validators.common.validate_clean_text]),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[apps.core.validators.common.validate_phone]),
        ),
    ]
