# Generated by Django 5.2.15 on 2026-07-03 06:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0003_companylocation_company_address_line_and_more"),
        ("it_recruitment", "0003_alter_jobseekerprofile_managers_and_more"),
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobLocation",
            fields=[
                (
                    "created_by_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=120)),
                ("state", models.CharField(blank=True, max_length=120)),
                ("city", models.CharField(blank=True, max_length=120)),
                ("office_address", models.CharField(blank=True, max_length=500)),
                (
                    "work_mode",
                    models.CharField(
                        choices=[
                            ("onsite", "Onsite"),
                            ("remote", "Remote"),
                            ("hybrid", "Hybrid"),
                        ],
                        default="onsite",
                        max_length=20,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "it_job_location",
            },
        ),
        migrations.AlterModelOptions(
            name="jobposting",
            options={"default_manager_name": "objects"},
        ),
        migrations.AddField(
            model_name="jobposting",
            name="application_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="benefits",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="category",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="city",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="country",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="department",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="education_requirement",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="hiring_manager",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="is_template",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="is_urgent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="job_code",
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="joining_timeline",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="moderation_remarks",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="office_address",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="roles_responsibilities",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="salary_visibility",
            field=models.CharField(
                choices=[
                    ("visible", "Visible"),
                    ("hidden", "Hidden"),
                    ("on_request", "On Request"),
                ],
                default="visible",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="state",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="vacancies",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="view_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("private", "Private"),
                    ("internal", "Internal"),
                ],
                default="public",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="work_mode",
            field=models.CharField(
                choices=[
                    ("onsite", "Onsite"),
                    ("remote", "Remote"),
                    ("hybrid", "Hybrid"),
                ],
                default="onsite",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="jobpostingskill",
            name="is_preferred",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="employment_type",
            field=models.CharField(
                choices=[
                    ("full_time", "Full Time"),
                    ("part_time", "Part Time"),
                    ("contract", "Contract"),
                    ("internship", "Internship"),
                    ("temporary", "Temporary"),
                    ("freelance", "Freelance"),
                ],
                default="full_time",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_approval", "Pending Approval"),
                    ("published", "Published"),
                    ("paused", "Paused"),
                    ("closed", "Closed"),
                    ("expired", "Expired"),
                    ("archived", "Archived"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="jobposting",
            index=models.Index(
                fields=["status", "is_featured"], name="it_job_post_status_50a7f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobposting",
            index=models.Index(
                fields=["company", "status"], name="it_job_post_company_c73cc4_idx"
            ),
        ),
        migrations.AddField(
            model_name="joblocation",
            name="job_posting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="jobs.jobposting",
            ),
        ),
    ]
