# Generated by Django 5.2.15 on 2026-07-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0004_production_indexes"),
        ("it_recruitment", "0003_alter_jobseekerprofile_managers_and_more"),
        ("jobs", "0002_joblocation_alter_jobposting_options_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="jobposting",
            index=models.Index(
                fields=["expires_at"], name="it_job_post_expires_c34ce6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobposting",
            index=models.Index(
                fields=["moderation_status"], name="it_job_post_moderat_70c23e_idx"
            ),
        ),
    ]
