# Generated by Django 5.2.15 on 2026-07-06 18:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0003_production_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="jobposting",
            name="it_job_post_moderat_70c23e_idx",
        ),
        migrations.RemoveField(
            model_name="jobposting",
            name="moderation_remarks",
        ),
        migrations.RemoveField(
            model_name="jobposting",
            name="moderation_status",
        ),
    ]
