# Generated by Django 5.2.15 on 2026-07-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_alter_company_benefits_alter_company_culture_and_more'),
        ('it_recruitment', '0015_alter_jobseekerprofile_current_company_and_more'),
        ('jobs', '0005_alter_jobposting_benefits_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['published_at'], name='it_job_post_publish_cc0b5e_idx'),
        ),
    ]
