# Generated by Django 5.2.15 on 2026-07-17 11:56

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import BtreeGinExtension, TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_alter_company_benefits_alter_company_culture_and_more'),
        ('it_recruitment', '0015_alter_jobseekerprofile_current_company_and_more'),
        ('jobs', '0006_jobposting_it_job_post_publish_cc0b5e_idx'),
    ]

    operations = [
        BtreeGinExtension(),
        TrigramExtension(),
        migrations.AddIndex(
            model_name='jobposting',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='job_title_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=django.contrib.postgres.indexes.GinIndex(fields=['company_name_snapshot'], name='job_comp_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=django.contrib.postgres.indexes.GinIndex(fields=['location'], name='job_loc_gin', opclasses=['gin_trgm_ops']),
        ),
    ]
