DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100
MIN_PAGE_SIZE = 1

DEFAULT_SEARCH_PARAM = "search"
DEFAULT_ORDERING_PARAM = "ordering"
DEFAULT_PAGE_PARAM = "page"
DEFAULT_PAGE_SIZE_PARAM = "page_size"

MAX_UPLOAD_SIZE_MB = 10
MAX_IMAGE_SIZE_MB = 5

REQUEST_ID_HEADER = "X-Request-ID"
TIMEZONE_HEADER = "X-Timezone"

STORAGE_BACKEND_LOCAL = "local"
STORAGE_BACKEND_S3 = "s3"
