from apps.core.constants.enums import PlatformRole

PERMISSION_VIEW = "view"
PERMISSION_CREATE = "create"
PERMISSION_UPDATE = "update"
PERMISSION_DELETE = "delete"
PERMISSION_ADMIN = "admin"

ROLE_PERMISSIONS = {
    PlatformRole.ADMIN: {
        PERMISSION_VIEW,
        PERMISSION_CREATE,
        PERMISSION_UPDATE,
        PERMISSION_DELETE,
        PERMISSION_ADMIN,
    },
    PlatformRole.RECRUITER: {PERMISSION_VIEW, PERMISSION_CREATE, PERMISSION_UPDATE},
    PlatformRole.JOB_SEEKER: {PERMISSION_VIEW, PERMISSION_CREATE, PERMISSION_UPDATE},
    PlatformRole.PROFESSOR: {PERMISSION_VIEW, PERMISSION_CREATE, PERMISSION_UPDATE},
    PlatformRole.COLLEGE: {PERMISSION_VIEW, PERMISSION_CREATE, PERMISSION_UPDATE},
}
