# Generated by Django 5.2.15 on 2026-07-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0002_billing_enterprise"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["status", "domain"], name="billing_inv_status_b6f646_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["bill_to_entity_type", "bill_to_entity_id"],
                name="billing_inv_bill_to_ea2e97_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["due_at"], name="billing_inv_due_at_51fb5f_idx"),
        ),
    ]
