# Generated by Django 5.2.15 on 2026-07-15 08:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_production_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalInvoiceConfiguration',
            fields=[
                ('created_by_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('business_name', models.CharField(default='EduNaukri', max_length=255)),
                ('invoice_header', models.CharField(default='TAX INVOICE', max_length=100)),
                ('business_address', models.TextField(default='EduNaukri Business Address')),
                ('gstin', models.CharField(blank=True, max_length=50)),
                ('pan', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('footer_text', models.TextField(blank=True)),
                ('thank_you_message', models.CharField(default='Thank you for choosing EduNaukri.', max_length=255)),
                ('terms_conditions', models.TextField(blank=True)),
                ('payment_notes', models.TextField(blank=True)),
                ('show_gstin', models.BooleanField(default=True)),
                ('show_pan', models.BooleanField(default=False)),
                ('show_phone', models.BooleanField(default=True)),
                ('show_email', models.BooleanField(default=True)),
                ('show_website', models.BooleanField(default=True)),
                ('show_coupon_discount', models.BooleanField(default=True)),
                ('show_tax_breakdown', models.BooleanField(default=True)),
                ('show_payment_method', models.BooleanField(default=True)),
                ('show_transaction_id', models.BooleanField(default=True)),
                ('show_subscription_validity', models.BooleanField(default=True)),
                ('show_terms', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Global Invoice Configuration',
                'verbose_name_plural': 'Global Invoice Configuration',
                'db_table': 'billing_invoice_configuration',
            },
        ),
    ]
