# Generated by Django 5.2.15 on 2026-07-15 09:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_globalinvoiceconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalinvoiceconfiguration',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='globalinvoiceconfiguration',
            name='fixed_recruitment_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='globalinvoiceconfiguration',
            name='gst_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='globalinvoiceconfiguration',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='globalinvoiceconfiguration',
            name='payment_due_days',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='globalinvoiceconfiguration',
            name='pricing_method',
            field=models.CharField(choices=[('percentage_ctc', 'Percentage of Annual CTC'), ('fixed_fee', 'Fixed Recruitment Fee')], default='percentage_ctc', max_length=50),
        ),
        migrations.AddField(
            model_name='globalinvoiceconfiguration',
            name='service_charge_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('8.33'), max_digits=5),
        ),
        migrations.AddField(
            model_name='globalinvoiceconfiguration',
            name='tax_calculation_mode',
            field=models.CharField(choices=[('cgst_sgst', 'CGST + SGST'), ('igst', 'IGST')], default='cgst_sgst', max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='candidate_annual_ctc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='candidate_job_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='candidate_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='igst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pricing_method_snapshot',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='service_charge_percentage_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='taxable_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
