# Generated by Django 5.2.15 on 2026-07-17 10:38

import apps.core.validators.common
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_globalinvoiceconfiguration_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalinvoiceconfiguration',
            name='business_name',
            field=models.CharField(default='EduNaukri', max_length=255, validators=[apps.core.validators.common.validate_organization_name]),
        ),
        migrations.AlterField(
            model_name='globalinvoiceconfiguration',
            name='fixed_recruitment_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='globalinvoiceconfiguration',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='globalinvoiceconfiguration',
            name='gstin',
            field=models.CharField(blank=True, max_length=50, validators=[apps.core.validators.common.validate_gst]),
        ),
        migrations.AlterField(
            model_name='globalinvoiceconfiguration',
            name='pan',
            field=models.CharField(blank=True, max_length=50, validators=[apps.core.validators.common.validate_pan]),
        ),
        migrations.AlterField(
            model_name='globalinvoiceconfiguration',
            name='phone',
            field=models.CharField(blank=True, max_length=50, validators=[apps.core.validators.common.validate_phone]),
        ),
        migrations.AlterField(
            model_name='globalinvoiceconfiguration',
            name='service_charge_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('8.33'), max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
