# Generated by Django 5.2.15 on 2026-07-17 11:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_alter_globalinvoiceconfiguration_business_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicestatushistory',
            name='changed_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['issued_at'], name='billing_inv_issued__60a8ee_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['paid_at'], name='billing_inv_paid_at_a017a2_idx'),
        ),
    ]
