# Generated by Django 5.2.15 on 2026-07-02 19:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StoredFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("it", "IT Recruitment"),
                            ("faculty", "Faculty Recruitment"),
                            ("platform", "Platform"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("resume", "Resume"),
                            ("cv", "CV"),
                            ("certificate", "Certificate"),
                            ("company_logo", "Company Logo"),
                            ("college_logo", "College Logo"),
                            ("invoice_pdf", "Invoice PDF"),
                            ("claim_document", "Claim Document"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("original_filename", models.CharField(max_length=500)),
                ("stored_filename", models.CharField(max_length=500)),
                ("storage_path", models.CharField(max_length=1000)),
                (
                    "storage_backend",
                    models.CharField(
                        choices=[("local", "Local Filesystem"), ("s3", "Amazon S3")],
                        default="local",
                        max_length=50,
                    ),
                ),
                ("mime_type", models.CharField(max_length=100)),
                ("file_size_bytes", models.BigIntegerField()),
                (
                    "checksum_sha256",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("owner_type", models.CharField(db_index=True, max_length=50)),
                ("owner_id", models.UUIDField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploading", "Uploading"),
                            ("active", "Active"),
                            ("quarantined", "Quarantined"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("parsed_data", models.JSONField(blank=True, null=True)),
                ("parsed_at", models.DateTimeField(blank=True, null=True)),
                ("uploaded_by_id", models.UUIDField(db_index=True)),
            ],
            options={
                "db_table": "storage_file",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["owner_type", "owner_id"], name="storage_file_owner_idx"
                    ),
                    models.Index(
                        fields=["domain", "file_type"],
                        name="storage_file_domain_type_idx",
                    ),
                ],
            },
        ),
    ]
