# Generated by Django 5.2.15 on 2026-07-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_storedfile_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedfile',
            name='file_type',
            field=models.CharField(choices=[('resume', 'Resume'), ('cv', 'CV'), ('certificate', 'Certificate'), ('profile_photo', 'Profile Photo'), ('company_logo', 'Company Logo'), ('college_logo', 'College Logo'), ('college_banner', 'College Banner'), ('invoice_pdf', 'Invoice PDF'), ('claim_document', 'Claim Document'), ('other', 'Other')], db_index=True, max_length=30),
        ),
    ]
