# Generated by Django 5.2.15 on 2026-07-17 10:38

import apps.core.validators.common
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_storedfile_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedfile',
            name='original_filename',
            field=models.CharField(max_length=500, validators=[apps.core.validators.common.validate_clean_text]),
        ),
        migrations.AlterField(
            model_name='storedfile',
            name='stored_filename',
            field=models.CharField(max_length=500, validators=[apps.core.validators.common.validate_clean_text]),
        ),
    ]
