# Generated by Django 5.2.15 on 2026-07-22 17:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0004_alter_storedfile_original_filename_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeFraudRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_code', models.CharField(db_index=True, max_length=60, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(help_text='Category e.g., Timeline, Formatting, AI_Gen', max_length=100)),
                ('default_weight', models.PositiveSmallIntegerField(default=10, help_text='Risk penalty weight')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resume Fraud Rule',
                'verbose_name_plural': 'Resume Fraud Rules',
                'ordering': ['rule_code'],
            },
        ),
        migrations.CreateModel(
            name='ResumeFraudAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(choices=[('it', 'IT Recruitment'), ('faculty', 'Faculty Recruitment')], db_index=True, default='it', max_length=20)),
                ('seeker_user_id', models.BigIntegerField(db_index=True, help_text='User ID of candidate')),
                ('resume_version', models.PositiveIntegerField(default=1, help_text='Incrementing version count')),
                ('trust_score', models.PositiveSmallIntegerField(default=100, help_text='Computed trust score (0 to 100)')),
                ('risk_score', models.PositiveSmallIntegerField(default=0, help_text='Computed risk score (0 to 100)')),
                ('confidence_score', models.DecimalField(decimal_places=2, default=1.0, help_text='Engine confidence level (0.00 to 1.00)', max_digits=4)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Risk')], db_index=True, default='LOW', max_length=20)),
                ('warning_count', models.PositiveSmallIntegerField(default=0, help_text='Total active warning count')),
                ('recommendation', models.CharField(choices=[('PASS', 'Pass'), ('FLAG_FOR_REVIEW', 'Flag for Review'), ('REJECT', 'Reject')], default='PASS', max_length=30)),
                ('analysis_duration_ms', models.PositiveIntegerField(blank=True, help_text='Execution time in milliseconds', null=True)),
                ('json_analysis_report', models.JSONField(blank=True, default=dict, help_text='Full detailed JSON analysis report and evidence breakdown')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if analysis failed')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stored_file', models.ForeignKey(blank=True, help_text='Reference to the uploaded file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_analyses', to='documents.storedfile')),
            ],
            options={
                'verbose_name': 'Resume Fraud Analysis',
                'verbose_name_plural': 'Resume Fraud Analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeFraudHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seeker_user_id', models.BigIntegerField(db_index=True)),
                ('domain', models.CharField(choices=[('it', 'IT Recruitment'), ('faculty', 'Faculty Recruitment')], default='it', max_length=20)),
                ('previous_trust_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('new_trust_score', models.PositiveSmallIntegerField()),
                ('score_delta', models.IntegerField(help_text='Difference between new and previous score')),
                ('change_reason', models.CharField(default='Resume Re-upload', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fraud_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_logs', to='resume_trust.resumefraudanalysis')),
            ],
            options={
                'verbose_name': 'Resume Fraud History',
                'verbose_name_plural': 'Resume Fraud Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeFraudWarning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_code', models.CharField(db_index=True, help_text='Rule identifier', max_length=60)),
                ('rule_name', models.CharField(max_length=150)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('evidence_snippet', models.TextField(blank=True, help_text='Extracted text evidence')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fraud_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='resume_trust.resumefraudanalysis')),
            ],
            options={
                'verbose_name': 'Resume Fraud Warning',
                'verbose_name_plural': 'Resume Fraud Warnings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='resumefraudanalysis',
            index=models.Index(fields=['domain', 'seeker_user_id'], name='resume_trus_domain_08d1d4_idx'),
        ),
        migrations.AddIndex(
            model_name='resumefraudanalysis',
            index=models.Index(fields=['stored_file'], name='resume_trus_stored__873e04_idx'),
        ),
        migrations.AddIndex(
            model_name='resumefraudanalysis',
            index=models.Index(fields=['risk_level'], name='resume_trus_risk_le_3776ae_idx'),
        ),
        migrations.AddIndex(
            model_name='resumefraudanalysis',
            index=models.Index(fields=['trust_score'], name='resume_trus_trust_s_e94c94_idx'),
        ),
        migrations.AddIndex(
            model_name='resumefraudanalysis',
            index=models.Index(fields=['created_at'], name='resume_trus_created_e3b666_idx'),
        ),
        migrations.AddIndex(
            model_name='resumefraudhistory',
            index=models.Index(fields=['seeker_user_id', 'domain'], name='resume_trus_seeker__da7bb0_idx'),
        ),
        migrations.AddIndex(
            model_name='resumefraudhistory',
            index=models.Index(fields=['created_at'], name='resume_trus_created_26b7e3_idx'),
        ),
        migrations.AddIndex(
            model_name='resumefraudwarning',
            index=models.Index(fields=['fraud_analysis', 'severity'], name='resume_trus_fraud_a_3c497d_idx'),
        ),
        migrations.AddIndex(
            model_name='resumefraudwarning',
            index=models.Index(fields=['rule_code'], name='resume_trus_rule_co_253306_idx'),
        ),
    ]
