# Generated by Django 5.2.15 on 2026-07-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_trust', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumefraudanalysis',
            name='seeker_user_id',
            field=models.CharField(db_index=True, help_text='User ID or UUID of candidate', max_length=64),
        ),
        migrations.AlterField(
            model_name='resumefraudhistory',
            name='seeker_user_id',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
