# Generated by Django 5.2.15 on 2026-07-03 18:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "created_by_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("author_name", models.CharField(max_length=200)),
                ("designation", models.CharField(blank=True, max_length=200)),
                ("organization_name", models.CharField(blank=True, max_length=200)),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("it", "IT Placement"),
                            ("faculty", "Faculty Placement"),
                        ],
                        db_index=True,
                        default="it",
                        max_length=20,
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField(default=5)),
                ("quote", models.TextField()),
                (
                    "days_to_hire",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "salary_increase_pct",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("joined_dream_company", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(db_index=True, default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "moderation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("flagged", "Flagged"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("public", "Public"), ("private", "Private")],
                        default="public",
                        max_length=20,
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "photo_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="testimonial_photos",
                        to="documents.storedfile",
                    ),
                ),
            ],
            options={
                "db_table": "common_testimonial",
                "ordering": ["-published_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["moderation_status", "is_active"],
                        name="common_test_moderat_46731c_idx",
                    ),
                    models.Index(
                        fields=["domain", "is_verified"],
                        name="common_test_domain_f946b6_idx",
                    ),
                ],
            },
        ),
    ]
