# Generated by Django 5.2.15 on 2026-07-04 05:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("org_name", models.CharField(max_length=200)),
                (
                    "domain",
                    models.CharField(
                        choices=[("it", "IT"), ("faculty", "Faculty")],
                        db_index=True,
                        default="it",
                        max_length=20,
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("job_posted", "Job Posted"),
                            ("faculty_posted", "Faculty Vacancy Posted"),
                            ("candidate_applied", "Candidate Applied"),
                            ("shortlisted", "Candidate Shortlisted"),
                            ("interview_scheduled", "Interview Scheduled"),
                            ("offer_released", "Offer Released"),
                            ("candidate_hired", "Candidate Hired"),
                            ("recruiter_verified", "Recruiter Verified"),
                            ("company_joined", "Company Joined"),
                            ("university_joined", "University Joined"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("headline", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "logo_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logos",
                        to="documents.storedfile",
                    ),
                ),
            ],
            options={
                "db_table": "common_platform_activity",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "created_at"],
                        name="common_plat_is_acti_c8faf1_idx",
                    )
                ],
            },
        ),
    ]
