# Generated by Django 5.2.15 on 2026-07-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_platformactivity"),
        ("documents", "0002_alter_storedfile_file_type"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="testimonial",
            name="common_test_moderat_46731c_idx",
        ),
        migrations.RemoveField(
            model_name="testimonial",
            name="moderation_status",
        ),
        migrations.AddIndex(
            model_name="testimonial",
            index=models.Index(
                fields=["is_active", "visibility"],
                name="common_test_is_acti_8bb182_idx",
            ),
        ),
    ]
