# Generated by Django 5.2.15 on 2026-07-02 19:41

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GuaranteeClaim",
            fields=[
                (
                    "created_by_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("it", "IT Recruitment"),
                            ("faculty", "Faculty Recruitment"),
                            ("platform", "Platform"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "application_entity_type",
                    models.CharField(
                        choices=[
                            ("it_job_application", "IT Job Application"),
                            ("faculty_application", "Faculty Application"),
                            ("it_job_posting", "IT Job Posting"),
                            ("faculty_vacancy", "Faculty Vacancy"),
                            ("it_company", "IT Company"),
                            ("faculty_college", "Faculty College"),
                            ("stored_file", "Stored File"),
                        ],
                        max_length=40,
                    ),
                ),
                ("application_entity_id", models.UUIDField(db_index=True)),
                (
                    "placement_fee_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("invoice_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "claim_type",
                    models.CharField(
                        choices=[("replacement", "Replacement"), ("refund", "Refund")],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("resolved", "Resolved"),
                        ],
                        db_index=True,
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "submitted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "billing_guarantee_claim",
            },
        ),
    ]
