# Generated by Django 5.2.15 on 2026-07-13 16:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_facultyapplication_college_rating'),
        ('colleges', '0005_remove_college_faculty_col_verific_d7d7a8_idx_and_more'),
        ('guarantee_claims', '0002_billing_enterprise'),
        ('invoices', '0003_production_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementClaim',
            fields=[
                ('created_by_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('claim_number', models.CharField(max_length=50, unique=True)),
                ('faculty_recruiter_id', models.UUIDField(db_index=True)),
                ('claim_reason', models.CharField(choices=[('absconded', 'Absconded'), ('left_without_notice', 'Left Without Notice'), ('failed_to_join', 'Failed to Join after Confirmed Joining'), ('other_review_required', 'Other (Review Required)')], max_length=50)),
                ('incident_date', models.DateField()),
                ('claim_description', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('more_information_required', 'More Information Required'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('refund_pending', 'Refund Pending'), ('refund_processing', 'Refund Processing'), ('refunded', 'Refunded'), ('refund_failed', 'Refund Failed'), ('closed', 'Closed')], db_index=True, default='submitted', max_length=50)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by_id', models.UUIDField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('refund_status', models.CharField(blank=True, max_length=50, null=True)),
                ('refund_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('supporting_documents', models.JSONField(blank=True, default=list)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placement_claims', to='applications.facultyapplication')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placement_claims', to='colleges.college')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='placement_claims', to='invoices.invoice')),
            ],
            options={
                'db_table': 'billing_placement_claim',
            },
        ),
        migrations.CreateModel(
            name='PlacementClaimHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('more_information_required', 'More Information Required'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('refund_pending', 'Refund Pending'), ('refund_processing', 'Refund Processing'), ('refunded', 'Refunded'), ('refund_failed', 'Refund Failed'), ('closed', 'Closed')], max_length=50, null=True)),
                ('to_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('more_information_required', 'More Information Required'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('refund_pending', 'Refund Pending'), ('refund_processing', 'Refund Processing'), ('refunded', 'Refunded'), ('refund_failed', 'Refund Failed'), ('closed', 'Closed')], max_length=50)),
                ('changed_by_id', models.UUIDField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='guarantee_claims.placementclaim')),
            ],
            options={
                'db_table': 'billing_placement_claim_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='placementclaim',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('status__in', ('rejected', 'closed', 'refund_failed')), _negated=True)), fields=('application',), name='unique_active_placement_claim'),
        ),
    ]
