# Generated by Django 5.2.15 on 2026-07-14 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_interviewevaluation'),
        ('colleges', '0006_college_completion_animation_shown_and_more'),
        ('guarantee_claims', '0003_placementclaim_placementclaimhistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementclaim',
            name='claim_type',
            field=models.CharField(choices=[('refund', 'Refund'), ('replacement', 'Replacement')], default='refund', max_length=20),
        ),
        migrations.AddField(
            model_name='placementclaim',
            name='company_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='placementclaim',
            name='job_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='placement_claims', to='applications.jobapplication'),
        ),
        migrations.AlterField(
            model_name='placementclaim',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='placement_claims', to='applications.facultyapplication'),
        ),
        migrations.AlterField(
            model_name='placementclaim',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='placement_claims', to='colleges.college'),
        ),
    ]
