# Generated by Django 5.2.15 on 2026-07-15 09:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_interviewevaluation'),
        ('guarantee_claims', '0004_placementclaim_claim_type_placementclaim_company_id_and_more'),
        ('invoices', '0005_globalinvoiceconfiguration_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuaranteeRefund',
            fields=[
                ('created_by_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('refund_number', models.CharField(max_length=50, unique=True)),
                ('recruiter_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('institution_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('original_invoice_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('approved_refund_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('refund_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=30)),
                ('payment_provider', models.CharField(blank=True, help_text='e.g. manual, razorpay, stripe', max_length=50)),
                ('provider_refund_id', models.CharField(blank=True, max_length=100)),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('approved_by_id', models.UUIDField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'billing_guarantee_refund',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReplacementCandidateWorkflow',
            fields=[
                ('created_by_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('workflow_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('search_active', 'Search Active'), ('candidate_identified', 'Candidate Identified'), ('candidate_selected', 'Candidate Selected'), ('candidate_joined', 'Candidate Joined'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='search_active', max_length=30)),
                ('search_started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'billing_guarantee_replacement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='guaranteeclaim',
            name='unique_active_claim_per_invoice',
        ),
        migrations.AddField(
            model_name='guaranteeclaim',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='guaranteeclaim',
            name='claim_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='guaranteeclaim',
            name='exit_reason',
            field=models.CharField(blank=True, choices=[('absconded', 'Candidate Absconded'), ('resigned', 'Candidate Resigned'), ('did_not_continue', 'Candidate Did Not Continue'), ('terminated', 'Candidate Terminated'), ('did_not_join', 'Candidate Did Not Join After Confirmation'), ('performance_issue', 'Performance Issue'), ('bgv_failure', 'Background Verification Failure'), ('other', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='guaranteeclaim',
            name='guarantee_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guaranteeclaim',
            name='guarantee_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guaranteeclaim',
            name='institution_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='guaranteeclaim',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guaranteeclaim',
            name='recruiter_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='guaranteeclaim',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='guaranteeclaim',
            name='replacement_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='guaranteeclaim',
            name='resolution_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='guaranteeclaim',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guaranteeclaim',
            name='claim_type',
            field=models.CharField(choices=[('replacement', 'Replacement'), ('refund', 'Refund'), ('platform_review', 'Platform Review')], max_length=20),
        ),
        migrations.AlterField(
            model_name='guaranteeclaim',
            name='resolution',
            field=models.CharField(blank=True, choices=[('refund', 'Refund'), ('replacement_candidate', 'Replacement Candidate'), ('rejected', 'Rejected')], max_length=30),
        ),
        migrations.AlterField(
            model_name='guaranteeclaim',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('more_information_required', 'More Information Required'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('refund_processing', 'Refund Processing'), ('refunded', 'Refunded'), ('replacement_search', 'Replacement Search'), ('replacement_completed', 'Replacement Completed'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], db_index=True, default='submitted', max_length=30),
        ),
        migrations.AlterField(
            model_name='guaranteeclaimhistory',
            name='from_status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('more_information_required', 'More Information Required'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('refund_processing', 'Refund Processing'), ('refunded', 'Refunded'), ('replacement_search', 'Replacement Search'), ('replacement_completed', 'Replacement Completed'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='guaranteeclaimhistory',
            name='to_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('more_information_required', 'More Information Required'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('refund_processing', 'Refund Processing'), ('refunded', 'Refunded'), ('replacement_search', 'Replacement Search'), ('replacement_completed', 'Replacement Completed'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], max_length=50),
        ),
        migrations.AddConstraint(
            model_name='guaranteeclaim',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('status__in', ('rejected', 'resolved', 'cancelled')), _negated=True)), fields=('invoice_id',), name='unique_active_claim_per_invoice'),
        ),
        migrations.AddField(
            model_name='guaranteerefund',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='guarantee_claims.guaranteeclaim'),
        ),
        migrations.AddField(
            model_name='guaranteerefund',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guarantee_refunds', to='invoices.invoice'),
        ),
        migrations.AddField(
            model_name='replacementcandidateworkflow',
            name='claim',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='replacement_workflow', to='guarantee_claims.guaranteeclaim'),
        ),
        migrations.AddField(
            model_name='replacementcandidateworkflow',
            name='original_faculty_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='original_replacements', to='applications.facultyapplication'),
        ),
        migrations.AddField(
            model_name='replacementcandidateworkflow',
            name='original_it_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='original_replacements', to='applications.jobapplication'),
        ),
        migrations.AddField(
            model_name='replacementcandidateworkflow',
            name='replacement_faculty_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fulfilled_replacements', to='applications.facultyapplication'),
        ),
        migrations.AddField(
            model_name='replacementcandidateworkflow',
            name='replacement_it_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fulfilled_replacements', to='applications.jobapplication'),
        ),
    ]
