# Generated by Django 5.2.15 on 2026-07-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarantee_claims', '0005_guaranteerefund_replacementcandidateworkflow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guaranteeclaim',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('more_information_required', 'More Information Required'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('refund_processing', 'Refund Processing'), ('refunded', 'Refunded'), ('replacement_search', 'Replacement Search'), ('replacement_completed', 'Replacement Completed'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled'), ('invalid_data', 'Invalid Data (Orphaned)'), ('archived', 'Archived')], db_index=True, default='submitted', max_length=30),
        ),
        migrations.AlterField(
            model_name='guaranteeclaimhistory',
            name='from_status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('more_information_required', 'More Information Required'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('refund_processing', 'Refund Processing'), ('refunded', 'Refunded'), ('replacement_search', 'Replacement Search'), ('replacement_completed', 'Replacement Completed'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled'), ('invalid_data', 'Invalid Data (Orphaned)'), ('archived', 'Archived')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='guaranteeclaimhistory',
            name='to_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('more_information_required', 'More Information Required'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('refund_processing', 'Refund Processing'), ('refunded', 'Refunded'), ('replacement_search', 'Replacement Search'), ('replacement_completed', 'Replacement Completed'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled'), ('invalid_data', 'Invalid Data (Orphaned)'), ('archived', 'Archived')], max_length=50),
        ),
    ]
