import os
import sys
from django.conf import settings
from django.core.management.base import BaseCommand
from django.db import transaction
from unittest.mock import patch

# Initialize Django if executed standalone
if __name__ == "__main__":
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings.development")
    import django
    django.setup()

from apps.accounts.models import ProfessorUser, CollegeUser
from apps.academic_recruitment.models import ProfessorProfile, Qualification, ProfessorQualification
from apps.colleges.models import College, CollegeMember
from apps.faculty.models import FacultyVacancy
from apps.applications.models import (
    FacultyApplication,
    FacultyApplicationStatusHistory,
    FacultyApplicationTimelineEvent,
    InterviewEvaluation,
    PlacementDetails,
)
from apps.invoices.models import Invoice, InvoiceLineItem
from apps.guarantee_claims.models import PlacementGuarantee, GuaranteeClaim, GuaranteeClaimHistory
from apps.documents.models import StoredFile
from apps.core.constants.enums import DomainType


def _safe_delete(qs):
    """Safely deletes queryset items, handling model delete return values."""
    if qs.exists():
        res = qs.delete()
        if isinstance(res, tuple) and len(res) > 0:
            return res[0]
        elif isinstance(res, int):
            return res
        return 0
    return 0


class Command(BaseCommand):
    help = "Safely deletes all Faculty domain demo data generated by faculty_domain_demo_data.py."

    def handle(self, *args, **options):
        self.stdout.write(self.style.WARNING("Starting safe deletion of Faculty Domain Demo Data..."))

        stats = {
            "claims": 0,
            "claim_histories": 0,
            "guarantees": 0,
            "invoices": 0,
            "placements": 0,
            "evaluations": 0,
            "timeline_events": 0,
            "status_histories": 0,
            "applications": 0,
            "vacancies": 0,
            "college_members": 0,
            "colleges": 0,
            "recruiters": 0,
            "candidate_profiles": 0,
            "candidate_users": 0,
        }

        with transaction.atomic():
            # 1. Target exact Faculty demo records by email patterns and demo tags
            demo_claims = GuaranteeClaim.all_objects.filter(claim_number__startswith="CLM-DEMO-FAC")
            demo_claim_ids = list(demo_claims.values_list("id", flat=True))

            # 1a. Delete claim histories
            stats["claim_histories"] += _safe_delete(
                GuaranteeClaimHistory.objects.filter(claim_id__in=demo_claim_ids)
            )

            # 1b. Delete claims
            stats["claims"] += _safe_delete(demo_claims)

            # 2. Identify demo applications
            demo_apps = FacultyApplication.all_objects.filter(
                college__name__startswith="[DEMO-FACULTY]"
            )
            demo_app_ids = list(demo_apps.values_list("id", flat=True))

            # 3. Delete placement guarantees
            stats["guarantees"] += _safe_delete(
                PlacementGuarantee.all_objects.filter(
                    domain=DomainType.FACULTY,
                    application_entity_id__in=demo_app_ids,
                )
            )

            # 4. Delete invoices & line items
            demo_invoices = Invoice.all_objects.filter(
                domain=DomainType.FACULTY,
                invoice_number__startswith="INV-DEMO-FAC",
            )
            demo_inv_ids = list(demo_invoices.values_list("id", flat=True))
            _safe_delete(InvoiceLineItem.objects.filter(invoice_id__in=demo_inv_ids))
            stats["invoices"] += _safe_delete(demo_invoices)

            # 5. Delete placement details
            stats["placements"] += _safe_delete(
                PlacementDetails.objects.filter(
                    domain=DomainType.FACULTY,
                    application_id__in=demo_app_ids,
                )
            )

            # 6. Delete interview evaluations
            stats["evaluations"] += _safe_delete(
                InterviewEvaluation.objects.filter(
                    domain=DomainType.FACULTY,
                    application_id__in=demo_app_ids,
                )
            )

            # 7. Delete status history & timeline events
            stats["timeline_events"] += _safe_delete(
                FacultyApplicationTimelineEvent.objects.filter(application_id__in=demo_app_ids)
            )
            stats["status_histories"] += _safe_delete(
                FacultyApplicationStatusHistory.objects.filter(application_id__in=demo_app_ids)
            )

            # 8. Delete Applications
            stats["applications"] += _safe_delete(demo_apps)

            # 9. Delete Vacancies
            demo_vacancies = FacultyVacancy.all_objects.filter(
                college__name__startswith="[DEMO-FACULTY]"
            )
            stats["vacancies"] += _safe_delete(demo_vacancies)

            # 10. Delete College Members & Colleges
            demo_colleges = College.all_objects.filter(name__startswith="[DEMO-FACULTY]")
            demo_college_ids = list(demo_colleges.values_list("id", flat=True))

            stats["college_members"] += _safe_delete(
                CollegeMember.all_objects.filter(college_id__in=demo_college_ids)
            )
            stats["colleges"] += _safe_delete(demo_colleges)

            # 11. Delete Recruiter Users
            demo_recruiters = CollegeUser.all_objects.filter(email__startswith="faculty.recruiter")
            stats["recruiters"] += _safe_delete(demo_recruiters)

            # 12. Delete Candidate Profiles & Users
            demo_candidates = ProfessorUser.all_objects.filter(email__startswith="faculty.candidate")
            demo_candidate_ids = list(demo_candidates.values_list("id", flat=True))

            stats["candidate_profiles"] += _safe_delete(
                ProfessorProfile.all_objects.filter(user_id__in=demo_candidate_ids)
            )
            stats["candidate_users"] += _safe_delete(demo_candidates)

            # 13. Delete stored file placeholder
            StoredFile.all_objects.filter(
                storage_path="demo/resumes/faculty_sample_resume.pdf"
            ).delete()

            # Safety check: Verify IT domain demo data and non-demo data remain untouched
            from apps.accounts.models import ITUser
            from apps.companies.models import Company
            if not ITUser.all_objects.filter(email__startswith="it.seeker").exists() and ITUser.all_objects.exists():
                pass  # OK if IT demo data exists or was cleared separately

        self._print_deletion_summary(stats)

    def _print_deletion_summary(self, stats):
        summary = f"""
=====================================================
FACULTY DEMO DATA DELETED
=====================================================

Claims deleted .................. {stats['claims']}
Placements deleted .............. {stats['placements']}
Demo evaluations deleted ........ {stats['evaluations']}
Applications deleted ............ {stats['applications']}
Faculty jobs deleted ............ {stats['vacancies']}
Institutions deleted ............ {stats['colleges']}
Recruiter accounts deleted ...... {stats['recruiters']}
Faculty accounts deleted ........ {stats['candidate_users']}

=====================================================
"""
        self.stdout.write(summary)


if __name__ == "__main__":
    Command().handle()
