# Generated by Django 5.2.15 on 2026-07-02 20:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("colleges", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="college",
            name="aicte_code",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="college",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="college",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="college",
            name="naac_grade",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="college",
            name="profile_status",
            field=models.CharField(
                choices=[("active", "Active"), ("deactivated", "Deactivated")],
                db_index=True,
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="college",
            name="profile_visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("private", "Private"),
                    ("employers_only", "Employers Only"),
                ],
                db_index=True,
                default="public",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="college",
            name="ugc_code",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name="CollegeDepartment",
            fields=[
                (
                    "created_by_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "college",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="colleges.college",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="colleges",
                        to="colleges.department",
                    ),
                ),
            ],
            options={
                "db_table": "faculty_college_department",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("college", "department"),
                        name="unique_college_department",
                    )
                ],
            },
        ),
    ]
