# Generated by Django 5.2.15 on 2026-07-03 04:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("colleges", "0002_college_aicte_code_college_contact_email_and_more"),
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstitutionCampus",
            fields=[
                (
                    "created_by_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("label", models.CharField(blank=True, max_length=150)),
                ("address_line", models.CharField(blank=True, max_length=500)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("district", models.CharField(blank=True, max_length=120)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=120)),
                ("pin_code", models.CharField(blank=True, max_length=10)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("is_main_campus", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "faculty_college_campus",
            },
        ),
        migrations.CreateModel(
            name="InstitutionDocument",
            fields=[
                (
                    "created_by_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("approval_certificate", "Approval Certificate"),
                            ("accreditation_certificate", "Accreditation Certificate"),
                            ("naac_document", "NAAC Document"),
                            ("aicte_document", "AICTE Document"),
                            ("ugc_document", "UGC Document"),
                            ("brochure", "Institution Brochure"),
                            ("logo", "Logo"),
                            ("campus_image", "Campus Image"),
                            ("other", "Other"),
                        ],
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "db_table": "faculty_college_document",
            },
        ),
        migrations.AlterModelOptions(
            name="college",
            options={"default_manager_name": "objects"},
        ),
        migrations.AddField(
            model_name="college",
            name="academic_calendar_reference",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="college",
            name="affiliated_university",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="college",
            name="alternate_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="college",
            name="autonomous_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="college",
            name="campus_area",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="college",
            name="country",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="college",
            name="courses_offered",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="college",
            name="cover_banner_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="college_banners",
                to="documents.storedfile",
            ),
        ),
        migrations.AddField(
            model_name="college",
            name="district",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="college",
            name="facebook_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="college",
            name="facilities",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="college",
            name="hostel_availability",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="college",
            name="infrastructure_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="college",
            name="instagram_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="college",
            name="institution_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("engineering", "Engineering College"),
                    ("arts_science", "Arts & Science College"),
                    ("medical", "Medical College"),
                    ("law", "Law College"),
                    ("management", "Management Institute"),
                    ("polytechnic", "Polytechnic"),
                    ("university", "University"),
                    ("deemed_university", "Deemed University"),
                    ("research_institute", "Research Institute"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="college",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="college",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="college",
            name="legal_name",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="college",
            name="linkedin_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="college",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="college",
            name="mission",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="college",
            name="nba_accreditation",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="college",
            name="number_of_faculty",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="college",
            name="number_of_students",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="college",
            name="ownership_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("government", "Government"),
                    ("private", "Private"),
                    ("aided", "Government Aided"),
                    ("autonomous", "Autonomous"),
                    ("deemed", "Deemed"),
                    ("public_private", "Public-Private Partnership"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="college",
            name="placement_cell_details",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="college",
            name="programs_offered",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="college",
            name="research_centers",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="college",
            name="transportation_facilities",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="college",
            name="twitter_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="college",
            name="verification_remarks",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="college",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="college",
            name="verified_by_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="college",
            name="vision",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="college",
            name="youtube_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="college",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                    ("suspended", "Suspended"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="collegemember",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("admin", "Administrator"),
                    ("member", "Member"),
                ],
                default="admin",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="college",
            index=models.Index(
                fields=["verification_status", "is_active"],
                name="faculty_col_verific_d7d7a8_idx",
            ),
        ),
        migrations.AddField(
            model_name="institutioncampus",
            name="college",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campuses",
                to="colleges.college",
            ),
        ),
        migrations.AddField(
            model_name="institutiondocument",
            name="college",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="colleges.college",
            ),
        ),
        migrations.AddField(
            model_name="institutiondocument",
            name="stored_file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="institution_documents",
                to="documents.storedfile",
            ),
        ),
    ]
