# Generated by Django 5.2.15 on 2026-07-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_auth_security_fields"),
        ("colleges", "0003_institutioncampus_institutiondocument_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="collegemember",
            index=models.Index(
                fields=["is_active", "is_deleted"],
                name="faculty_col_is_acti_85c006_idx",
            ),
        ),
    ]
