# Generated by Django 5.2.15 on 2026-07-06 18:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("colleges", "0004_production_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="college",
            name="faculty_col_verific_d7d7a8_idx",
        ),
        migrations.RemoveField(
            model_name="college",
            name="verification_remarks",
        ),
        migrations.RemoveField(
            model_name="college",
            name="verification_status",
        ),
        migrations.RemoveField(
            model_name="college",
            name="verified_at",
        ),
        migrations.RemoveField(
            model_name="college",
            name="verified_by_id",
        ),
    ]
