# Generated by Django 5.2.15 on 2026-07-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0005_remove_college_faculty_col_verific_d7d7a8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='completion_animation_shown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='college',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='college',
            name='profile_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='profile_completeness',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='college',
            name='profile_completion_fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
