# Generated by Django 5.2.15 on 2026-07-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0007_remove_college_is_active_college_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='status',
        ),
        migrations.AddField(
            model_name='college',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
