# Generated by Django 5.2.15 on 2026-07-17 10:38

import apps.core.validators.common
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0008_remove_college_status_college_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='affiliated_university',
            field=models.CharField(blank=True, max_length=300, validators=[apps.core.validators.common.validate_organization_name]),
        ),
        migrations.AlterField(
            model_name='college',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=20, validators=[apps.core.validators.common.validate_phone]),
        ),
        migrations.AlterField(
            model_name='college',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, validators=[apps.core.validators.common.validate_phone]),
        ),
        migrations.AlterField(
            model_name='college',
            name='description',
            field=models.TextField(blank=True, validators=[apps.core.validators.common.validate_clean_text]),
        ),
        migrations.AlterField(
            model_name='college',
            name='established_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800)]),
        ),
        migrations.AlterField(
            model_name='college',
            name='facilities',
            field=models.TextField(blank=True, validators=[apps.core.validators.common.validate_clean_text]),
        ),
        migrations.AlterField(
            model_name='college',
            name='infrastructure_description',
            field=models.TextField(blank=True, validators=[apps.core.validators.common.validate_clean_text]),
        ),
        migrations.AlterField(
            model_name='college',
            name='legal_name',
            field=models.CharField(blank=True, max_length=300, validators=[apps.core.validators.common.validate_organization_name]),
        ),
        migrations.AlterField(
            model_name='college',
            name='mission',
            field=models.TextField(blank=True, validators=[apps.core.validators.common.validate_clean_text]),
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(max_length=300, validators=[apps.core.validators.common.validate_organization_name]),
        ),
        migrations.AlterField(
            model_name='college',
            name='number_of_faculty',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='college',
            name='number_of_students',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='college',
            name='placement_cell_details',
            field=models.TextField(blank=True, validators=[apps.core.validators.common.validate_clean_text]),
        ),
        migrations.AlterField(
            model_name='college',
            name='research_centers',
            field=models.TextField(blank=True, validators=[apps.core.validators.common.validate_clean_text]),
        ),
        migrations.AlterField(
            model_name='college',
            name='vision',
            field=models.TextField(blank=True, validators=[apps.core.validators.common.validate_clean_text]),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=200, unique=True, validators=[apps.core.validators.common.validate_organization_name]),
        ),
    ]
