# Generated by Django 5.2.15 on 2026-07-02 20:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academic_recruitment", "0001_initial"),
        ("accounts", "0003_auth_security_fields"),
        ("colleges", "0002_college_aicte_code_college_contact_email_and_more"),
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfessorDepartment",
            fields=[
                (
                    "created_by_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "faculty_professor_department",
            },
        ),
        migrations.AddField(
            model_name="professorprofile",
            name="expected_salary",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="professorprofile",
            name="highest_qualification",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="professorprofile",
            name="industry_experience_years",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="professorprofile",
            name="preferred_locations",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="professorprofile",
            name="profile_photo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="professor_photos",
                to="documents.storedfile",
            ),
        ),
        migrations.AddField(
            model_name="professorprofile",
            name="profile_status",
            field=models.CharField(
                choices=[("active", "Active"), ("deactivated", "Deactivated")],
                db_index=True,
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="professorprofile",
            name="profile_visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("private", "Private"),
                    ("employers_only", "Employers Only"),
                ],
                db_index=True,
                default="private",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="professorprofile",
            name="publications_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="professorprofile",
            name="teaching_experience_years",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="professorprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("profile_completeness__gte", 0), ("profile_completeness__lte", 100)
                ),
                name="professor_profile_completeness_range",
            ),
        ),
        migrations.AddField(
            model_name="professordepartment",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="professors",
                to="colleges.department",
            ),
        ),
        migrations.AddField(
            model_name="professordepartment",
            name="professor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="academic_recruitment.professorprofile",
            ),
        ),
        migrations.AddConstraint(
            model_name="professordepartment",
            constraint=models.UniqueConstraint(
                fields=("professor", "department"), name="unique_professor_department"
            ),
        ),
    ]
