# Generated by Django 5.2.15 on 2026-07-03 10:36

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "academic_recruitment",
            "0002_professordepartment_professorprofile_expected_salary_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="professorprofile",
            managers=[
                ("profiles", django.db.models.manager.Manager()),
            ],
        ),
    ]
