# Generated by Django 5.2.15 on 2026-07-06 10:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academic_recruitment", "0003_faculty_application_enterprise"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfessorAccountSettings",
            fields=[
                (
                    "created_by_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("notify_vacancy_recommendations", models.BooleanField(default=True)),
                ("notify_institution_messages", models.BooleanField(default=True)),
                ("notify_application_updates", models.BooleanField(default=True)),
                ("notify_interviews", models.BooleanField(default=True)),
                ("notify_offers", models.BooleanField(default=True)),
                ("notify_marketing", models.BooleanField(default=False)),
                ("notify_security_alerts", models.BooleanField(default=True)),
                ("notify_profile_views", models.BooleanField(default=True)),
                ("notify_cv_downloads", models.BooleanField(default=True)),
                ("notify_weekly_digest", models.BooleanField(default=True)),
                ("allow_institution_cv_download", models.BooleanField(default=True)),
                ("allow_institution_contact", models.BooleanField(default=True)),
                ("show_email_on_profile", models.BooleanField(default=False)),
                ("show_phone_on_profile", models.BooleanField(default=False)),
                ("password_changed_at", models.DateTimeField(blank=True, null=True)),
                ("phone_verified", models.BooleanField(default=False)),
                (
                    "professor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_settings",
                        to="academic_recruitment.professorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "faculty_professor_account_settings",
            },
        ),
    ]
