# Generated by Django 5.2.15 on 2026-07-06 11:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academic_recruitment", "0004_professor_account_settings"),
        ("documents", "0002_alter_storedfile_file_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="professorprofile",
            name="completion_animation_shown",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="professorprofile",
            name="profile_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="professorprofile",
            name="profile_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="professorprofile",
            name="profile_completion_fingerprint",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.CreateModel(
            name="ProfessorCertification",
            fields=[
                (
                    "created_by_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=300)),
                ("issuing_organization", models.CharField(blank=True, max_length=300)),
                (
                    "category",
                    models.CharField(db_index=True, default="other", max_length=30),
                ),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("credential_id", models.CharField(blank=True, max_length=200)),
                ("credential_url", models.URLField(blank=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "certificate_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="professor_certifications",
                        to="documents.storedfile",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to="academic_recruitment.professorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "faculty_professor_certification",
                "ordering": ["-issue_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["professor", "category"],
                        name="faculty_pro_profess_9f2ce4_idx",
                    ),
                    models.Index(
                        fields=["expiry_date"], name="faculty_pro_expiry__415105_idx"
                    ),
                ],
            },
        ),
    ]
