# Generated by Django 5.2.15 on 2026-07-06 14:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academic_recruitment", "0005_professor_completion_and_certifications"),
        ("accounts", "0002_collegeuser_professoruser_ituserrole"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollegeAccountSettings",
            fields=[
                (
                    "created_by_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("notify_new_applications", models.BooleanField(default=True)),
                ("notify_application_updates", models.BooleanField(default=True)),
                ("notify_interviews", models.BooleanField(default=True)),
                ("notify_offers", models.BooleanField(default=True)),
                ("notify_vacancy_updates", models.BooleanField(default=True)),
                ("notify_verification_alerts", models.BooleanField(default=True)),
                ("notify_faculty_messages", models.BooleanField(default=True)),
                ("notify_marketing", models.BooleanField(default=False)),
                ("notify_security_alerts", models.BooleanField(default=True)),
                ("notify_weekly_digest", models.BooleanField(default=True)),
                ("show_email_to_applicants", models.BooleanField(default=False)),
                ("show_phone_to_applicants", models.BooleanField(default=False)),
                ("allow_direct_applicant_contact", models.BooleanField(default=True)),
                ("password_changed_at", models.DateTimeField(blank=True, null=True)),
                ("phone_verified", models.BooleanField(default=False)),
                (
                    "college_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_settings",
                        to="accounts.collegeuser",
                    ),
                ),
            ],
            options={
                "db_table": "faculty_college_account_settings",
            },
        ),
    ]
