# Generated by Django 5.2.15 on 2026-07-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academic_recruitment", "0006_college_account_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professorprofile",
            name="moderation_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("flagged", "Flagged"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
