# Generated by Django 5.2.15 on 2026-07-13 09:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_recruitment', '0007_alter_professorprofile_moderation_status'),
        ('documents', '0003_alter_storedfile_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedResume',
            fields=[
                ('created_by_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('extracted_skills', models.JSONField(blank=True, default=list)),
                ('extracted_education', models.JSONField(blank=True, default=list)),
                ('extracted_experience', models.JSONField(blank=True, default=list)),
                ('extracted_headline', models.CharField(blank=True, max_length=255)),
                ('raw_text', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('cv_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_resumes', to='documents.storedfile')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_resume', to='academic_recruitment.professorprofile')),
            ],
            options={
                'db_table': 'faculty_parsed_resume',
            },
        ),
    ]
