# Generated by Django 5.2.15 on 2026-07-17 10:38

import apps.core.validators.common
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_recruitment', '0008_parsedresume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professorprofile',
            name='current_designation',
            field=models.CharField(blank=True, max_length=150, validators=[apps.core.validators.common.validate_clean_text]),
        ),
        migrations.AlterField(
            model_name='professorprofile',
            name='current_institution',
            field=models.CharField(blank=True, max_length=300, validators=[apps.core.validators.common.validate_organization_name]),
        ),
        migrations.AlterField(
            model_name='professorprofile',
            name='expected_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='professorprofile',
            name='experience_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='professorprofile',
            name='first_name',
            field=models.CharField(max_length=100, validators=[apps.core.validators.common.validate_clean_text]),
        ),
        migrations.AlterField(
            model_name='professorprofile',
            name='industry_experience_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='professorprofile',
            name='last_name',
            field=models.CharField(max_length=100, validators=[apps.core.validators.common.validate_clean_text]),
        ),
        migrations.AlterField(
            model_name='professorprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[apps.core.validators.common.validate_phone]),
        ),
        migrations.AlterField(
            model_name='professorprofile',
            name='publications_count',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='professorprofile',
            name='research_interests',
            field=models.TextField(blank=True, validators=[apps.core.validators.common.validate_clean_text]),
        ),
        migrations.AlterField(
            model_name='professorprofile',
            name='teaching_experience_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
