# Generated by Django 5.2.15 on 2026-08-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_recruitment', '0009_alter_professorprofile_current_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professorprofile',
            name='github_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='professorprofile',
            name='google_scholar_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='professorprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='professorprofile',
            name='orcid_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='professorprofile',
            name='portfolio_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='professorprofile',
            name='researchgate_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='professorprofile',
            name='x_twitter_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
