# Generated by Django 5.2.15 on 2026-08-10 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_recruitment', '0010_professorprofile_github_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professorprofile',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='professorprofile',
            name='google_scholar_url',
        ),
        migrations.RemoveField(
            model_name='professorprofile',
            name='orcid_url',
        ),
        migrations.RemoveField(
            model_name='professorprofile',
            name='portfolio_url',
        ),
        migrations.RemoveField(
            model_name='professorprofile',
            name='researchgate_url',
        ),
        migrations.RemoveField(
            model_name='professorprofile',
            name='x_twitter_url',
        ),
    ]
