# Generated by Django 5.2.15 on 2026-07-02 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("applications", "0001_initial"),
        ("faculty", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="facultyapplication",
            name="vacancy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="faculty.facultyvacancy",
            ),
        ),
        migrations.AddField(
            model_name="facultyapplicationstatushistory",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_history",
                to="applications.facultyapplication",
            ),
        ),
    ]
