# Generated by Django 5.2.15 on 2026-07-02 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("applications", "0002_initial"),
        ("documents", "0001_initial"),
        ("it_recruitment", "0001_initial"),
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="job_posting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="jobs.jobposting",
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="job_seeker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="it_recruitment.jobseekerprofile",
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="resume_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="job_applications",
                to="documents.storedfile",
            ),
        ),
        migrations.AddField(
            model_name="jobapplicationstatushistory",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_history",
                to="applications.jobapplication",
            ),
        ),
        migrations.AddConstraint(
            model_name="facultyapplication",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("vacancy", "professor"),
                name="unique_active_faculty_application",
            ),
        ),
        migrations.AddConstraint(
            model_name="jobapplication",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("job_posting", "job_seeker"),
                name="unique_active_job_application",
            ),
        ),
    ]
