# Generated by Django 5.2.15 on 2026-07-03 08:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0003_initial"),
        ("companies", "0003_companylocation_company_address_line_and_more"),
        ("documents", "0001_initial"),
        ("it_recruitment", "0003_alter_jobseekerprofile_managers_and_more"),
        ("jobs", "0002_joblocation_alter_jobposting_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobApplicationTimelineEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Application Created"),
                            ("status_changed", "Status Changed"),
                            ("recruiter_comment", "Recruiter Comment"),
                            ("candidate_action", "Candidate Action"),
                            ("withdraw", "Withdraw"),
                            ("offer", "Offer"),
                            ("hire", "Hire"),
                            ("reject", "Reject"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("applied", "Applied"),
                            ("under_review", "Under Review"),
                            ("shortlisted", "Shortlisted"),
                            ("interview_scheduled", "Interview Scheduled"),
                            ("interview_completed", "Interview Completed"),
                            ("offer_released", "Offer Released"),
                            ("offer_accepted", "Offer Accepted"),
                            ("offer_declined", "Offer Declined"),
                            ("hired", "Hired"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                            ("expired", "Expired"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("applied", "Applied"),
                            ("under_review", "Under Review"),
                            ("shortlisted", "Shortlisted"),
                            ("interview_scheduled", "Interview Scheduled"),
                            ("interview_completed", "Interview Completed"),
                            ("offer_released", "Offer Released"),
                            ("offer_accepted", "Offer Accepted"),
                            ("offer_declined", "Offer Declined"),
                            ("hired", "Hired"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                            ("expired", "Expired"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, null=True)),
                (
                    "actor_domain",
                    models.CharField(
                        choices=[
                            ("it", "IT Recruitment"),
                            ("faculty", "Faculty Recruitment"),
                            ("platform", "Platform"),
                        ],
                        default="it",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "db_table": "it_application_timeline_event",
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="candidate_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="job_applications",
                to="companies.company",
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="company_name_snapshot",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="current_location",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="expected_salary",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="hired_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="internal_remarks",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="notice_period",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="recruiter_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="resume_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("direct", "Direct"),
                    ("referral", "Referral"),
                    ("job_board", "Job Board"),
                    ("agency", "Agency"),
                    ("career_fair", "Career Fair"),
                    ("internal", "Internal"),
                    ("other", "Other"),
                ],
                default="direct",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("applied", "Applied"),
                    ("under_review", "Under Review"),
                    ("shortlisted", "Shortlisted"),
                    ("interview_scheduled", "Interview Scheduled"),
                    ("interview_completed", "Interview Completed"),
                    ("offer_released", "Offer Released"),
                    ("offer_accepted", "Offer Accepted"),
                    ("offer_declined", "Offer Declined"),
                    ("hired", "Hired"),
                    ("rejected", "Rejected"),
                    ("withdrawn", "Withdrawn"),
                    ("expired", "Expired"),
                ],
                db_index=True,
                default="applied",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="jobapplicationstatushistory",
            name="from_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("applied", "Applied"),
                    ("under_review", "Under Review"),
                    ("shortlisted", "Shortlisted"),
                    ("interview_scheduled", "Interview Scheduled"),
                    ("interview_completed", "Interview Completed"),
                    ("offer_released", "Offer Released"),
                    ("offer_accepted", "Offer Accepted"),
                    ("offer_declined", "Offer Declined"),
                    ("hired", "Hired"),
                    ("rejected", "Rejected"),
                    ("withdrawn", "Withdrawn"),
                    ("expired", "Expired"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="jobapplicationstatushistory",
            name="to_status",
            field=models.CharField(
                choices=[
                    ("applied", "Applied"),
                    ("under_review", "Under Review"),
                    ("shortlisted", "Shortlisted"),
                    ("interview_scheduled", "Interview Scheduled"),
                    ("interview_completed", "Interview Completed"),
                    ("offer_released", "Offer Released"),
                    ("offer_accepted", "Offer Accepted"),
                    ("offer_declined", "Offer Declined"),
                    ("hired", "Hired"),
                    ("rejected", "Rejected"),
                    ("withdrawn", "Withdrawn"),
                    ("expired", "Expired"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["status", "company"], name="it_job_appl_status_5d29b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["job_posting", "status"], name="it_job_appl_job_pos_435651_idx"
            ),
        ),
        migrations.AddField(
            model_name="jobapplicationtimelineevent",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timeline",
                to="applications.jobapplication",
            ),
        ),
    ]
