# Generated by Django 5.2.15 on 2026-07-03 10:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academic_recruitment", "0003_faculty_application_enterprise"),
        ("applications", "0005_migrate_application_statuses"),
        ("colleges", "0003_institutioncampus_institutiondocument_and_more"),
        ("documents", "0001_initial"),
        ("faculty", "0002_facultyvacancycampus_alter_facultyvacancy_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacultyApplicationTimelineEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Application Created"),
                            ("status_changed", "Status Changed"),
                            ("college_comment", "College Comment"),
                            ("professor_action", "Professor Action"),
                            ("withdraw", "Withdraw"),
                            ("offer", "Offer"),
                            ("joined", "Joined"),
                            ("reject", "Reject"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("applied", "Applied"),
                            ("under_review", "Application Under Review"),
                            ("academic_verification", "Academic Verification"),
                            ("department_review", "Department Review"),
                            ("principal_review", "Principal Review"),
                            ("management_approval", "Management Approval"),
                            ("interview_scheduled", "Interview Scheduled"),
                            ("interview_completed", "Interview Completed"),
                            ("offer_released", "Offer Released"),
                            ("offer_accepted", "Offer Accepted"),
                            ("offer_declined", "Offer Declined"),
                            ("joined", "Joined"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                            ("expired", "Expired"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("applied", "Applied"),
                            ("under_review", "Application Under Review"),
                            ("academic_verification", "Academic Verification"),
                            ("department_review", "Department Review"),
                            ("principal_review", "Principal Review"),
                            ("management_approval", "Management Approval"),
                            ("interview_scheduled", "Interview Scheduled"),
                            ("interview_completed", "Interview Completed"),
                            ("offer_released", "Offer Released"),
                            ("offer_accepted", "Offer Accepted"),
                            ("offer_declined", "Offer Declined"),
                            ("joined", "Joined"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                            ("expired", "Expired"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, null=True)),
                (
                    "actor_domain",
                    models.CharField(
                        choices=[
                            ("it", "IT Recruitment"),
                            ("faculty", "Faculty Recruitment"),
                            ("platform", "Platform"),
                        ],
                        default="faculty",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "db_table": "faculty_application_timeline_event",
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.AddField(
            model_name="facultyapplication",
            name="certificates_snapshot",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="facultyapplication",
            name="college",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="faculty_applications",
                to="colleges.college",
            ),
        ),
        migrations.AddField(
            model_name="facultyapplication",
            name="college_name_snapshot",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="facultyapplication",
            name="college_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="facultyapplication",
            name="current_designation",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="facultyapplication",
            name="current_institution",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="facultyapplication",
            name="cv_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="facultyapplication",
            name="department",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="facultyapplication",
            name="expected_salary",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="facultyapplication",
            name="experience_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="facultyapplication",
            name="internal_remarks",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="facultyapplication",
            name="joined_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facultyapplication",
            name="professor_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="facultyapplication",
            name="qualification_snapshot",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="facultyapplication",
            name="research_publications_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="facultyapplication",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("direct", "Direct"),
                    ("referral", "Referral"),
                    ("job_board", "Job Board"),
                    ("agency", "Agency"),
                    ("career_fair", "Career Fair"),
                    ("internal", "Internal"),
                    ("other", "Other"),
                ],
                default="direct",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="facultyapplication",
            name="specialization_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="facultyapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("applied", "Applied"),
                    ("under_review", "Application Under Review"),
                    ("academic_verification", "Academic Verification"),
                    ("department_review", "Department Review"),
                    ("principal_review", "Principal Review"),
                    ("management_approval", "Management Approval"),
                    ("interview_scheduled", "Interview Scheduled"),
                    ("interview_completed", "Interview Completed"),
                    ("offer_released", "Offer Released"),
                    ("offer_accepted", "Offer Accepted"),
                    ("offer_declined", "Offer Declined"),
                    ("joined", "Joined"),
                    ("rejected", "Rejected"),
                    ("withdrawn", "Withdrawn"),
                    ("expired", "Expired"),
                ],
                db_index=True,
                default="applied",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="facultyapplicationstatushistory",
            name="from_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("applied", "Applied"),
                    ("under_review", "Application Under Review"),
                    ("academic_verification", "Academic Verification"),
                    ("department_review", "Department Review"),
                    ("principal_review", "Principal Review"),
                    ("management_approval", "Management Approval"),
                    ("interview_scheduled", "Interview Scheduled"),
                    ("interview_completed", "Interview Completed"),
                    ("offer_released", "Offer Released"),
                    ("offer_accepted", "Offer Accepted"),
                    ("offer_declined", "Offer Declined"),
                    ("joined", "Joined"),
                    ("rejected", "Rejected"),
                    ("withdrawn", "Withdrawn"),
                    ("expired", "Expired"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="facultyapplicationstatushistory",
            name="to_status",
            field=models.CharField(
                choices=[
                    ("applied", "Applied"),
                    ("under_review", "Application Under Review"),
                    ("academic_verification", "Academic Verification"),
                    ("department_review", "Department Review"),
                    ("principal_review", "Principal Review"),
                    ("management_approval", "Management Approval"),
                    ("interview_scheduled", "Interview Scheduled"),
                    ("interview_completed", "Interview Completed"),
                    ("offer_released", "Offer Released"),
                    ("offer_accepted", "Offer Accepted"),
                    ("offer_declined", "Offer Declined"),
                    ("joined", "Joined"),
                    ("rejected", "Rejected"),
                    ("withdrawn", "Withdrawn"),
                    ("expired", "Expired"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="facultyapplication",
            index=models.Index(
                fields=["status", "college"], name="faculty_app_status_de62de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="facultyapplication",
            index=models.Index(
                fields=["vacancy", "status"], name="faculty_app_vacancy_ec781e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="facultyapplication",
            index=models.Index(
                fields=["professor", "status"], name="faculty_app_profess_175b68_idx"
            ),
        ),
        migrations.AddField(
            model_name="facultyapplicationtimelineevent",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timeline",
                to="applications.facultyapplication",
            ),
        ),
    ]
