# Generated by Django 5.2.15 on 2026-07-04 10:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0007_migrate_faculty_application_statuses"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobApplicationInterview",
            fields=[
                (
                    "created_by_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("it", "IT Recruitment"),
                            ("faculty", "Faculty Recruitment"),
                            ("platform", "Platform"),
                        ],
                        default="it",
                        max_length=20,
                    ),
                ),
                (
                    "interview_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "round_type",
                    models.CharField(
                        choices=[
                            ("hr", "HR Round"),
                            ("technical", "Technical Round"),
                            ("managerial", "Managerial Round"),
                            ("final", "Final Round"),
                            ("demo", "Demo Class"),
                            ("panel", "Panel Interview"),
                            ("other", "Other"),
                        ],
                        default="technical",
                        max_length=30,
                    ),
                ),
                ("round_label", models.CharField(blank=True, max_length=120)),
                (
                    "interview_type",
                    models.CharField(default="Technical Interview", max_length=120),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("phone", "Phone"),
                        ],
                        default="online",
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(db_index=True)),
                ("duration_minutes", models.PositiveSmallIntegerField(default=45)),
                ("timezone_label", models.CharField(default="IST", max_length=64)),
                ("meet_url", models.URLField(blank=True, max_length=500)),
                ("location", models.CharField(blank=True, max_length=300)),
                ("panel", models.JSONField(blank=True, default=list)),
                ("instructions", models.TextField(blank=True)),
                ("required_documents", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("confirmed", "Confirmed"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("rescheduled", "Rescheduled"),
                        ],
                        db_index=True,
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("candidate_confirmed", models.BooleanField(default=False)),
                ("candidate_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("feedback", models.JSONField(blank=True, default=dict)),
                ("feedback_shared", models.BooleanField(default=False)),
                ("reminder_sent_at", models.JSONField(blank=True, default=dict)),
                ("scheduled_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="applications.jobapplication",
                    ),
                ),
            ],
            options={
                "db_table": "it_job_application_interview",
                "ordering": ["-scheduled_at"],
                "indexes": [
                    models.Index(
                        fields=["application", "status"],
                        name="it_job_appl_applica_730219_idx",
                    ),
                    models.Index(
                        fields=["scheduled_at", "status"],
                        name="it_job_appl_schedul_875ccb_idx",
                    ),
                ],
            },
        ),
    ]
