# Generated by Django 5.2.15 on 2026-07-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_add_shortlisted_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('under_review', 'Application Under Review'), ('shortlisted', 'Shortlisted'), ('academic_verification', 'Academic Verification'), ('department_review', 'Department Review'), ('principal_review', 'Principal Review'), ('management_approval', 'Management Approval'), ('interview_scheduled', 'Interview Scheduled'), ('interview_completed', 'Interview Completed'), ('offer_released', 'Offer Released'), ('offer_accepted', 'Offer Accepted'), ('offer_declined', 'Offer Declined'), ('selected', 'Selected'), ('joining_in_progress', 'Joining in Progress'), ('joined', 'Joined'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired')], db_index=True, default='applied', max_length=30),
        ),
        migrations.AlterField(
            model_name='facultyapplicationstatushistory',
            name='from_status',
            field=models.CharField(blank=True, choices=[('applied', 'Applied'), ('under_review', 'Application Under Review'), ('shortlisted', 'Shortlisted'), ('academic_verification', 'Academic Verification'), ('department_review', 'Department Review'), ('principal_review', 'Principal Review'), ('management_approval', 'Management Approval'), ('interview_scheduled', 'Interview Scheduled'), ('interview_completed', 'Interview Completed'), ('offer_released', 'Offer Released'), ('offer_accepted', 'Offer Accepted'), ('offer_declined', 'Offer Declined'), ('selected', 'Selected'), ('joining_in_progress', 'Joining in Progress'), ('joined', 'Joined'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='facultyapplicationstatushistory',
            name='to_status',
            field=models.CharField(choices=[('applied', 'Applied'), ('under_review', 'Application Under Review'), ('shortlisted', 'Shortlisted'), ('academic_verification', 'Academic Verification'), ('department_review', 'Department Review'), ('principal_review', 'Principal Review'), ('management_approval', 'Management Approval'), ('interview_scheduled', 'Interview Scheduled'), ('interview_completed', 'Interview Completed'), ('offer_released', 'Offer Released'), ('offer_accepted', 'Offer Accepted'), ('offer_declined', 'Offer Declined'), ('selected', 'Selected'), ('joining_in_progress', 'Joining in Progress'), ('joined', 'Joined'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired')], max_length=30),
        ),
        migrations.AlterField(
            model_name='facultyapplicationtimelineevent',
            name='from_status',
            field=models.CharField(blank=True, choices=[('applied', 'Applied'), ('under_review', 'Application Under Review'), ('shortlisted', 'Shortlisted'), ('academic_verification', 'Academic Verification'), ('department_review', 'Department Review'), ('principal_review', 'Principal Review'), ('management_approval', 'Management Approval'), ('interview_scheduled', 'Interview Scheduled'), ('interview_completed', 'Interview Completed'), ('offer_released', 'Offer Released'), ('offer_accepted', 'Offer Accepted'), ('offer_declined', 'Offer Declined'), ('selected', 'Selected'), ('joining_in_progress', 'Joining in Progress'), ('joined', 'Joined'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='facultyapplicationtimelineevent',
            name='to_status',
            field=models.CharField(blank=True, choices=[('applied', 'Applied'), ('under_review', 'Application Under Review'), ('shortlisted', 'Shortlisted'), ('academic_verification', 'Academic Verification'), ('department_review', 'Department Review'), ('principal_review', 'Principal Review'), ('management_approval', 'Management Approval'), ('interview_scheduled', 'Interview Scheduled'), ('interview_completed', 'Interview Completed'), ('offer_released', 'Offer Released'), ('offer_accepted', 'Offer Accepted'), ('offer_declined', 'Offer Declined'), ('selected', 'Selected'), ('joining_in_progress', 'Joining in Progress'), ('joined', 'Joined'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('interview_completed', 'Interview Completed'), ('offer_released', 'Offer Released'), ('offer_accepted', 'Offer Accepted'), ('offer_declined', 'Offer Declined'), ('selected', 'Selected'), ('joining_in_progress', 'Joining in Progress'), ('joined', 'Joined'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired')], db_index=True, default='applied', max_length=30),
        ),
        migrations.AlterField(
            model_name='jobapplicationstatushistory',
            name='from_status',
            field=models.CharField(blank=True, choices=[('applied', 'Applied'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('interview_completed', 'Interview Completed'), ('offer_released', 'Offer Released'), ('offer_accepted', 'Offer Accepted'), ('offer_declined', 'Offer Declined'), ('selected', 'Selected'), ('joining_in_progress', 'Joining in Progress'), ('joined', 'Joined'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplicationstatushistory',
            name='to_status',
            field=models.CharField(choices=[('applied', 'Applied'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('interview_completed', 'Interview Completed'), ('offer_released', 'Offer Released'), ('offer_accepted', 'Offer Accepted'), ('offer_declined', 'Offer Declined'), ('selected', 'Selected'), ('joining_in_progress', 'Joining in Progress'), ('joined', 'Joined'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired')], max_length=30),
        ),
        migrations.AlterField(
            model_name='jobapplicationtimelineevent',
            name='from_status',
            field=models.CharField(blank=True, choices=[('applied', 'Applied'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('interview_completed', 'Interview Completed'), ('offer_released', 'Offer Released'), ('offer_accepted', 'Offer Accepted'), ('offer_declined', 'Offer Declined'), ('selected', 'Selected'), ('joining_in_progress', 'Joining in Progress'), ('joined', 'Joined'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplicationtimelineevent',
            name='to_status',
            field=models.CharField(blank=True, choices=[('applied', 'Applied'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('interview_completed', 'Interview Completed'), ('offer_released', 'Offer Released'), ('offer_accepted', 'Offer Accepted'), ('offer_declined', 'Offer Declined'), ('selected', 'Selected'), ('joining_in_progress', 'Joining in Progress'), ('joined', 'Joined'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired')], max_length=30, null=True),
        ),
    ]
