# Generated by Django 5.2.15 on 2026-07-14 07:06

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_alter_facultyapplication_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementDetails',
            fields=[
                ('created_by_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('domain', models.CharField(choices=[('it', 'IT Recruitment'), ('faculty', 'Faculty Recruitment'), ('platform', 'Platform')], max_length=20)),
                ('application_id', models.UUIDField(db_index=True)),
                ('selected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('selected_by_id', models.UUIDField(blank=True, null=True)),
                ('expected_joining_date', models.DateField(blank=True, null=True)),
                ('offered_designation', models.CharField(blank=True, max_length=200)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('work_location', models.CharField(blank=True, max_length=200)),
                ('employment_type', models.CharField(blank=True, max_length=100)),
                ('agreed_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('offer_reference_number', models.CharField(blank=True, max_length=100)),
                ('joining_notes', models.TextField(blank=True)),
                ('actual_joining_date', models.DateField(blank=True, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=100)),
                ('joining_confirmed_notes', models.TextField(blank=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('joined_by_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recruitment_placement_details',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('domain', 'application_id'), name='unique_placement_details_per_application')],
            },
        ),
    ]
