# Generated by Django 5.2.15 on 2026-07-14 07:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_placementdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewEvaluation',
            fields=[
                ('created_by_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('domain', models.CharField(choices=[('it', 'IT Recruitment'), ('faculty', 'Faculty Recruitment'), ('platform', 'Platform')], max_length=20)),
                ('application_id', models.UUIDField(db_index=True)),
                ('technical_rating', models.PositiveSmallIntegerField(default=3)),
                ('communication_rating', models.PositiveSmallIntegerField(default=3)),
                ('subject_knowledge', models.PositiveSmallIntegerField(default=3)),
                ('teaching_skills', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('industry_skills', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('culture_fit', models.PositiveSmallIntegerField(default=3)),
                ('overall_rating', models.PositiveSmallIntegerField(default=3)),
                ('interview_notes', models.TextField(blank=True)),
                ('recommendation', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'recruitment_interview_evaluation',
            },
        ),
    ]
