# Generated by Django 5.2.15 on 2026-07-17 11:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_alter_facultyapplication_expected_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyapplication',
            name='applied_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='facultyapplicationstatushistory',
            name='changed_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='facultyapplicationtimelineevent',
            name='occurred_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='applied_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='jobapplicationstatushistory',
            name='changed_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='jobapplicationtimelineevent',
            name='occurred_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
