"""Allowed IT job application status transitions (enterprise workflow)."""

ALLOWED_IT_TRANSITIONS = {
    None: {"applied"},
    "applied": {
        "under_review",
        "shortlisted",
        "interview_scheduled",
        "rejected",
        "withdrawn",
        "expired",
    },
    "under_review": {
        "shortlisted",
        "interview_scheduled",
        "rejected",
        "withdrawn",
    },
    "shortlisted": {
        "under_review",
        "interview_scheduled",
        "selected",
        "offer_released",
        "rejected",
        "withdrawn",
    },
    "interview_scheduled": {
        "shortlisted",
        "interview_completed",
        "selected",
        "offer_released",
        "rejected",
        "withdrawn",
    },
    "interview_completed": {
        "selected",
        "offer_released",
        "rejected",
        "withdrawn",
    },
    "offer_released": {
        "offer_accepted",
        "offer_declined",
        "selected",
        "rejected",
        "withdrawn",
    },
    "offer_accepted": {
        "selected",
        "joining_in_progress",
        "joined",
        "hired",
        "rejected",
        "withdrawn",
    },
    "offer_declined": set(),
    "selected": {
        "offer_released",
        "joining_in_progress",
        "joined",
        "hired",
        "rejected",
        "withdrawn",
    },
    "joining_in_progress": {"joined", "hired", "rejected", "withdrawn"},
    "joined": set(),
    "hired": set(),
    "rejected": set(),
    "withdrawn": set(),
    "expired": set(),
}

# Enterprise faculty application workflow (Academic Recruitment domain).
ALLOWED_FACULTY_TRANSITIONS = {
    None: {"applied"},
    "applied": {"under_review", "shortlisted", "rejected", "withdrawn", "expired"},
    "under_review": {"shortlisted", "academic_verification", "rejected", "withdrawn"},
    "shortlisted": {"interview_scheduled", "rejected", "withdrawn"},
    "academic_verification": {"department_review", "rejected", "withdrawn"},
    "department_review": {"principal_review", "rejected", "withdrawn"},
    "principal_review": {"management_approval", "rejected", "withdrawn"},
    "management_approval": {"interview_scheduled", "rejected", "withdrawn"},
    "interview_scheduled": {
        "management_approval",
        "shortlisted",
        "interview_completed",
        "rejected",
        "withdrawn",
    },
    "interview_completed": {"selected", "rejected", "withdrawn"},
    "selected": {"joining_in_progress", "rejected", "withdrawn"},
    "joining_in_progress": {"joined", "rejected", "withdrawn"},
    "joined": set(),
    "rejected": set(),
    "withdrawn": set(),
    "expired": set(),
}
