from django.urls import path

from apps.academic_recruitment.views.college_portal import (
    CollegeAnalyticsView,
    CollegeApplicationDetailView,
    CollegeApplicationsView,
    CollegeDashboardView,
    CollegeInterviewsView,
    CollegeMessagesView,
    CollegeNotificationReadView,
    CollegeNotificationsMarkAllReadView,
    CollegeNotificationsView,
    CollegeProfileView,
    CollegeSettingsView,
    CollegeVacanciesView,
    CollegeVacancyCreateView,
    CollegeVacancyEditView,
    CollegeShortlistedCandidatesView,
    CollegeSelectedCandidatesView,
    CollegeJoinedCandidatesView,
)
from apps.guarantee_claims.views.api import RecruiterGuaranteeClaimAPIView
from apps.invoices.views.recruiter import RecruiterInvoicesView
from apps.academic_recruitment.views.college_dashboard_api import (
    CollegeDashboardInsightsAPIView,
    CollegeAnalyticsInsightsAPIView,
    CollegeProfileCompletionAnimationAPIView,
)
from apps.academic_recruitment.views.college_portal_api import (
    CollegeApplicationCvAPIView,
    CollegeApplicationNotesAPIView,
    CollegeApplicationProfileModalAPIView,
    CollegeApplicationsListAPIView,
    CollegeNotificationsPollAPIView,
    CollegeApplicationStatusAPIView,
    CollegeInstitutionAPIView,
    CollegeInstitutionImageUploadAPIView,
    CollegeInterviewCancelAPIView,
    CollegeInterviewCompleteAPIView,
    CollegeInterviewsListAPIView,
    CollegeInterviewRescheduleAPIView,
    CollegeInterviewScheduleAPIView,
    CollegeVacanciesListAPIView,
    CollegeVacancyArchiveAPIView,
    CollegeVacancyCloseAPIView,
    CollegeVacancyDeleteAPIView,
    CollegeVacancyDuplicateAPIView,
    CollegeVacancyPauseAPIView,
    CollegeVacancyPublishAPIView,
    CollegeVacancyReopenAPIView,
    CollegeApplicationSelectAPIView,
    CollegeApplicationSetJoiningAPIView,
    CollegeApplicationConfirmJoinedAPIView,
    CollegeApplicationReportExitAPIView,
)
from apps.academic_recruitment.views.college_settings_api import (
    CollegeSettingsAccountAPIView,
    CollegeSettingsAuditAPIView,
    CollegeSettingsConnectedAPIView,
    CollegeSettingsDeleteAccountAPIView,
    CollegeSettingsNotificationsAPIView,
    CollegeSettingsPasswordAPIView,
    CollegeSettingsPrivacyAPIView,
    CollegeSettingsRevokeSessionsAPIView,
    CollegeSettingsSessionDetailAPIView,
    CollegeSettingsSessionsAPIView,
)

urlpatterns = [
    path("invoices/", RecruiterInvoicesView.as_view(), name="college_invoices"),
    path("dashboard/", CollegeDashboardView.as_view(), name="college_dashboard"),
    path(
        "vacancies/create/",
        CollegeVacancyCreateView.as_view(),
        name="college_vacancy_create",
    ),
    path(
        "vacancies/<uuid:vacancy_id>/edit/",
        CollegeVacancyEditView.as_view(),
        name="college_vacancy_edit",
    ),
    path("vacancies/", CollegeVacanciesView.as_view(), name="college_vacancies"),
    path(
        "applications/", CollegeApplicationsView.as_view(), name="college_applications"
    ),
    path("interviews/", CollegeInterviewsView.as_view(), name="college_interviews"),
    path(
        "applications/<uuid:application_id>/",
        CollegeApplicationDetailView.as_view(),
        name="college_application_detail",
    ),
    path(
        "applications/<uuid:application_id>/claim/",
        RecruiterGuaranteeClaimAPIView.as_view(),
        name="college_submit_claim",
    ),
    path("analytics/", CollegeAnalyticsView.as_view(), name="college_analytics"),
    path("profile/", CollegeProfileView.as_view(), name="college_profile"),
    path("messages/", CollegeMessagesView.as_view(), name="college_messages"),
    path(
        "notifications/",
        CollegeNotificationsView.as_view(),
        name="college_notifications",
    ),
    path(
        "notifications/<uuid:notification_id>/read/",
        CollegeNotificationReadView.as_view(),
        name="college_notification_read",
    ),
    path(
        "notifications/mark-all-read/",
        CollegeNotificationsMarkAllReadView.as_view(),
        name="college_notifications_mark_all_read",
    ),
    path("settings/", CollegeSettingsView.as_view(), name="college_settings"),
    path("candidates/shortlisted/", CollegeShortlistedCandidatesView.as_view(), name="college_shortlisted_dashboard"),
    path("candidates/selected/", CollegeSelectedCandidatesView.as_view(), name="college_selected_dashboard"),
    path("candidates/joined/", CollegeJoinedCandidatesView.as_view(), name="college_joined_dashboard"),
    path(
        "api/dashboard/insights/",
        CollegeDashboardInsightsAPIView.as_view(),
        name="college_dashboard_insights_api",
    ),
    path(
        "api/notifications/poll/",
        CollegeNotificationsPollAPIView.as_view(),
        name="college_notifications_poll_api",
    ),
    path(
        "api/profile/completion-animation/",
        CollegeProfileCompletionAnimationAPIView.as_view(),
        name="college_profile_completion_animation_api",
    ),
    path(
        "api/analytics/insights/",
        CollegeAnalyticsInsightsAPIView.as_view(),
        name="college_analytics_insights_api",
    ),
    path(
        "api/institution/",
        CollegeInstitutionAPIView.as_view(),
        name="college_institution_api",
    ),
    path(
        "api/institution/image/<str:image_type>/",
        CollegeInstitutionImageUploadAPIView.as_view(),
        name="college_institution_image_api",
    ),
    path(
        "api/vacancies/",
        CollegeVacanciesListAPIView.as_view(),
        name="college_vacancies_list_api",
    ),
    path(
        "api/vacancies/<uuid:vacancy_id>/publish/",
        CollegeVacancyPublishAPIView.as_view(),
        name="college_vacancy_publish_api",
    ),
    path(
        "api/vacancies/<uuid:vacancy_id>/pause/",
        CollegeVacancyPauseAPIView.as_view(),
        name="college_vacancy_pause_api",
    ),
    path(
        "api/vacancies/<uuid:vacancy_id>/close/",
        CollegeVacancyCloseAPIView.as_view(),
        name="college_vacancy_close_api",
    ),
    path(
        "api/vacancies/<uuid:vacancy_id>/reopen/",
        CollegeVacancyReopenAPIView.as_view(),
        name="college_vacancy_reopen_api",
    ),
    path(
        "api/vacancies/<uuid:vacancy_id>/duplicate/",
        CollegeVacancyDuplicateAPIView.as_view(),
        name="college_vacancy_duplicate_api",
    ),
    path(
        "api/vacancies/<uuid:vacancy_id>/archive/",
        CollegeVacancyArchiveAPIView.as_view(),
        name="college_vacancy_archive_api",
    ),
    path(
        "api/vacancies/<uuid:vacancy_id>/delete/",
        CollegeVacancyDeleteAPIView.as_view(),
        name="college_vacancy_delete_api",
    ),
    path(
        "api/applications/",
        CollegeApplicationsListAPIView.as_view(),
        name="college_applications_list_api",
    ),
    path(
        "api/applications/<uuid:application_id>/profile/",
        CollegeApplicationProfileModalAPIView.as_view(),
        name="college_application_profile_api",
    ),
    path(
        "api/applications/<uuid:application_id>/status/",
        CollegeApplicationStatusAPIView.as_view(),
        name="college_application_status_api",
    ),
    path(
        "api/applications/<uuid:application_id>/notes/",
        CollegeApplicationNotesAPIView.as_view(),
        name="college_application_notes_api",
    ),
    path(
        "api/applications/<uuid:application_id>/cv/",
        CollegeApplicationCvAPIView.as_view(),
        name="college_application_cv_api",
    ),
    path(
        "api/applications/<uuid:application_id>/select/",
        CollegeApplicationSelectAPIView.as_view(),
        name="college_application_select_api",
    ),
    path(
        "api/applications/<uuid:application_id>/joining/",
        CollegeApplicationSetJoiningAPIView.as_view(),
        name="college_application_joining_api",
    ),
    path(
        "api/applications/<uuid:application_id>/confirm-joined/",
        CollegeApplicationConfirmJoinedAPIView.as_view(),
        name="college_application_confirm_joined_api",
    ),
    path(
        "api/applications/<uuid:application_id>/report-exit/",
        CollegeApplicationReportExitAPIView.as_view(),
        name="college_application_report_exit_api",
    ),
    path(
        "api/interviews/",
        CollegeInterviewsListAPIView.as_view(),
        name="college_interviews_list_api",
    ),
    path(
        "api/interviews/<uuid:application_id>/schedule/",
        CollegeInterviewScheduleAPIView.as_view(),
        name="college_interview_schedule_api",
    ),
    path(
        "api/interviews/<uuid:application_id>/reschedule/",
        CollegeInterviewRescheduleAPIView.as_view(),
        name="college_interview_reschedule_api",
    ),
    path(
        "api/interviews/<uuid:application_id>/cancel/",
        CollegeInterviewCancelAPIView.as_view(),
        name="college_interview_cancel_api",
    ),
    path(
        "api/interviews/<uuid:application_id>/complete/",
        CollegeInterviewCompleteAPIView.as_view(),
        name="college_interview_complete_api",
    ),
    path(
        "api/settings/account/",
        CollegeSettingsAccountAPIView.as_view(),
        name="college_settings_account_api",
    ),
    path(
        "api/settings/password/",
        CollegeSettingsPasswordAPIView.as_view(),
        name="college_settings_password_api",
    ),
    path(
        "api/settings/notifications/",
        CollegeSettingsNotificationsAPIView.as_view(),
        name="college_settings_notifications_api",
    ),
    path(
        "api/settings/privacy/",
        CollegeSettingsPrivacyAPIView.as_view(),
        name="college_settings_privacy_api",
    ),
    path(
        "api/settings/sessions/",
        CollegeSettingsSessionsAPIView.as_view(),
        name="college_settings_sessions_api",
    ),
    path(
        "api/settings/sessions/<uuid:session_id>/",
        CollegeSettingsSessionDetailAPIView.as_view(),
        name="college_settings_session_detail_api",
    ),
    path(
        "api/settings/sessions/revoke-others/",
        CollegeSettingsRevokeSessionsAPIView.as_view(),
        name="college_settings_revoke_sessions_api",
    ),
    path(
        "api/settings/delete/",
        CollegeSettingsDeleteAccountAPIView.as_view(),
        name="college_settings_delete_api",
    ),
    path(
        "api/settings/audit/",
        CollegeSettingsAuditAPIView.as_view(),
        name="college_settings_audit_api",
    ),
    path(
        "api/settings/connected/<str:provider>/",
        CollegeSettingsConnectedAPIView.as_view(),
        name="college_settings_connected_detail_api",
    ),
    path(
        "api/settings/connected/",
        CollegeSettingsConnectedAPIView.as_view(),
        name="college_settings_connected_api",
    ),
]
