# Generated by Django 5.2.15 on 2026-07-02 19:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("it", "IT Recruitment"),
                            ("faculty", "Faculty Recruitment"),
                            ("platform", "Platform"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=100)),
                (
                    "entity_type",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                ("entity_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "actor_type",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("it_user", "IT User"),
                            ("professor", "Professor"),
                            ("college", "College"),
                            ("system", "System"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                (
                    "request_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("payload_hash", models.CharField(blank=True, max_length=64)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("occurred_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "audit_event",
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(
                        fields=["domain", "event_type", "-occurred_at"],
                        name="audit_domain_event_idx",
                    )
                ],
            },
        ),
    ]
