# Generated by Django 5.2.15 on 2026-07-03 08:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_auth_security_fields"),
        ("colleges", "0003_institutioncampus_institutiondocument_and_more"),
        ("faculty", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacultyVacancyCampus",
            fields=[
                (
                    "created_by_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=120)),
                ("state", models.CharField(blank=True, max_length=120)),
                ("district", models.CharField(blank=True, max_length=120)),
                ("city", models.CharField(blank=True, max_length=120)),
                ("campus", models.CharField(blank=True, max_length=200)),
                (
                    "work_type",
                    models.CharField(
                        choices=[
                            ("onsite", "Onsite"),
                            ("hybrid", "Hybrid"),
                            ("remote", "Remote Teaching"),
                        ],
                        default="onsite",
                        max_length=20,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "faculty_vacancy_campus",
            },
        ),
        migrations.AlterModelOptions(
            name="facultyvacancy",
            options={"default_manager_name": "objects"},
        ),
        migrations.AddField(
            model_name="facultyvacancy",
            name="accommodation",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="facultyvacancy",
            name="administrative_responsibilities",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="facultyvacancy",
            name="application_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facultyvacancy",
            name="benefits",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="facultyvacancy",
            name="campus",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="facultyvacancy",
            name="city",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="facultyvacancy",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facultyvacancy",
            name="contract_duration",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="facultyvacancy",
            name="country",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="facultyvacancy",
            name="department",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="facultyvacancy",
            name="designation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("professor", "Professor"),
                    ("associate_professor", "Associate Professor"),
                    ("assistant_professor", "Assistant Professor"),
                    ("lecturer", "Lecturer"),
                    ("senior_lecturer", "Senior Lecturer"),
                    ("head_of_department", "Head of Department"),
                    ("dean", "Dean"),
                    ("research_fellow", "Research Fellow"),
                    ("visiting_faculty", "Visiting Faculty"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="facultyvacancy",
            name="district",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="facultyvacancy",
            name="experience_max",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facultyvacancy",
            name="facilities",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="facultyvacancy",
            name="hiring_committee",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="facultyvacancy",
            name="industry_experience",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facultyvacancy",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="facultyvacancy",
            name="is_template",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="facultyvacancy",
            name="is_urgent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="facultyvacancy",
            name="joining_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facultyvacancy",
            name="minimum_qualification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bachelors", "Bachelor's"),
                    ("masters", "Master's"),
                    ("mphil", "M.Phil"),
                    ("phd", "Ph.D"),
                    ("postdoc", "Post-Doctoral"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="facultyvacancy",
            name="moderation_remarks",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="facultyvacancy",
            name="preferred_qualification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bachelors", "Bachelor's"),
                    ("masters", "Master's"),
                    ("mphil", "M.Phil"),
                    ("phd", "Ph.D"),
                    ("postdoc", "Post-Doctoral"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="facultyvacancy",
            name="qualification_required",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="facultyvacancy",
            name="recruitment_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("regular", "Regular"),
                    ("contractual", "Contractual"),
                    ("guest", "Guest"),
                    ("deputation", "Deputation"),
                    ("ad_hoc", "Ad Hoc"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="facultyvacancy",
            name="research_expectations",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="facultyvacancy",
            name="research_experience",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facultyvacancy",
            name="roles_responsibilities",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="facultyvacancy",
            name="salary_visibility",
            field=models.CharField(
                choices=[
                    ("visible", "Visible"),
                    ("hidden", "Hidden"),
                    ("on_request", "On Request"),
                ],
                default="visible",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="facultyvacancy",
            name="specialization_required",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="facultyvacancy",
            name="state",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="facultyvacancy",
            name="teaching_responsibilities",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="facultyvacancy",
            name="vacancy_code",
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name="facultyvacancy",
            name="vacancy_count",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="facultyvacancy",
            name="view_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="facultyvacancy",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("private", "Private"),
                    ("internal", "Internal"),
                ],
                default="public",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="facultyvacancy",
            name="work_type",
            field=models.CharField(
                choices=[
                    ("onsite", "Onsite"),
                    ("hybrid", "Hybrid"),
                    ("remote", "Remote Teaching"),
                ],
                default="onsite",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="facultyvacancy",
            name="employment_type",
            field=models.CharField(
                choices=[
                    ("full_time", "Full Time"),
                    ("part_time", "Part Time"),
                    ("contract", "Contract"),
                    ("visiting", "Visiting"),
                    ("adjunct", "Adjunct"),
                    ("tenure_track", "Tenure Track"),
                ],
                default="full_time",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="facultyvacancy",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_approval", "Pending Approval"),
                    ("published", "Published"),
                    ("paused", "Paused"),
                    ("closed", "Closed"),
                    ("expired", "Expired"),
                    ("archived", "Archived"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="facultyvacancy",
            index=models.Index(
                fields=["status", "is_featured"], name="faculty_vac_status_14a986_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="facultyvacancy",
            index=models.Index(
                fields=["college", "status"], name="faculty_vac_college_e5ff5f_idx"
            ),
        ),
        migrations.AddField(
            model_name="facultyvacancycampus",
            name="vacancy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campuses",
                to="faculty.facultyvacancy",
            ),
        ),
    ]
