# Generated by Django 5.2.15 on 2026-07-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_auth_security_fields"),
        ("colleges", "0004_production_indexes"),
        ("faculty", "0002_facultyvacancycampus_alter_facultyvacancy_options_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="facultyvacancy",
            index=models.Index(
                fields=["expires_at"], name="faculty_vac_expires_0f8535_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="facultyvacancy",
            index=models.Index(
                fields=["moderation_status"], name="faculty_vac_moderat_c7d530_idx"
            ),
        ),
    ]
