# Generated by Django 5.2.15 on 2026-07-06 18:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("faculty", "0003_production_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="facultyvacancy",
            name="faculty_vac_moderat_c7d530_idx",
        ),
        migrations.RemoveField(
            model_name="facultyvacancy",
            name="moderation_remarks",
        ),
        migrations.RemoveField(
            model_name="facultyvacancy",
            name="moderation_status",
        ),
    ]
