# Generated by Django 5.2.15 on 2026-07-17 10:38

import apps.core.validators.common
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_remove_facultyvacancy_faculty_vac_moderat_c7d530_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyvacancy',
            name='accommodation',
            field=models.CharField(blank=True, max_length=255, validators=[apps.core.validators.common.validate_clean_text]),
        ),
        migrations.AlterField(
            model_name='facultyvacancy',
            name='administrative_responsibilities',
            field=models.TextField(blank=True, validators=[apps.core.validators.common.validate_clean_text]),
        ),
        migrations.AlterField(
            model_name='facultyvacancy',
            name='benefits',
            field=models.TextField(blank=True, validators=[apps.core.validators.common.validate_clean_text]),
        ),
        migrations.AlterField(
            model_name='facultyvacancy',
            name='description',
            field=models.TextField(validators=[apps.core.validators.common.validate_clean_text]),
        ),
        migrations.AlterField(
            model_name='facultyvacancy',
            name='experience_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='facultyvacancy',
            name='experience_min',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='facultyvacancy',
            name='facilities',
            field=models.TextField(blank=True, validators=[apps.core.validators.common.validate_clean_text]),
        ),
        migrations.AlterField(
            model_name='facultyvacancy',
            name='industry_experience',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='facultyvacancy',
            name='qualification_required',
            field=models.TextField(blank=True, validators=[apps.core.validators.common.validate_clean_text]),
        ),
        migrations.AlterField(
            model_name='facultyvacancy',
            name='requirements',
            field=models.TextField(blank=True, validators=[apps.core.validators.common.validate_clean_text]),
        ),
        migrations.AlterField(
            model_name='facultyvacancy',
            name='research_expectations',
            field=models.TextField(blank=True, validators=[apps.core.validators.common.validate_clean_text]),
        ),
        migrations.AlterField(
            model_name='facultyvacancy',
            name='research_experience',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='facultyvacancy',
            name='roles_responsibilities',
            field=models.TextField(blank=True, validators=[apps.core.validators.common.validate_clean_text]),
        ),
        migrations.AlterField(
            model_name='facultyvacancy',
            name='salary_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='facultyvacancy',
            name='salary_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='facultyvacancy',
            name='specialization_required',
            field=models.TextField(blank=True, validators=[apps.core.validators.common.validate_clean_text]),
        ),
        migrations.AlterField(
            model_name='facultyvacancy',
            name='teaching_responsibilities',
            field=models.TextField(blank=True, validators=[apps.core.validators.common.validate_clean_text]),
        ),
        migrations.AlterField(
            model_name='facultyvacancy',
            name='title',
            field=models.CharField(max_length=300, validators=[apps.core.validators.common.validate_clean_text]),
        ),
    ]
