# Generated by Django 5.2.15 on 2026-07-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auth_security_fields'),
        ('colleges', '0009_alter_college_affiliated_university_and_more'),
        ('faculty', '0005_alter_facultyvacancy_accommodation_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='facultyvacancy',
            index=models.Index(fields=['published_at'], name='faculty_vac_publish_03c1dd_idx'),
        ),
    ]
