# Generated by Django 5.2.15 on 2026-07-19 10:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this social account link.', primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('linkedin', 'LinkedIn'), ('microsoft', 'Microsoft'), ('github', 'GitHub')], db_index=True, help_text='OAuth identity provider name.', max_length=20, verbose_name='Provider')),
                ('provider_user_id', models.CharField(db_index=True, help_text='Unique user ID assigned by the external provider.', max_length=255, verbose_name='Provider User ID')),
                ('email', models.EmailField(blank=True, default='', help_text='Email address returned by the provider (may differ from the local user email).', max_length=254, verbose_name='Email')),
                ('display_name', models.CharField(blank=True, default='', help_text='Full display name from the provider.', max_length=255, verbose_name='Display Name')),
                ('profile_picture', models.URLField(blank=True, default='', help_text='URL of the profile picture from the provider.', max_length=500, verbose_name='Profile Picture')),
                ('access_token', models.TextField(blank=True, help_text='OAuth access token used to call provider APIs on behalf of the user. Should be encrypted at rest in production.', null=True, verbose_name='Access Token')),
                ('refresh_token', models.TextField(blank=True, help_text='OAuth refresh token used to obtain new access tokens after expiry. Should be encrypted at rest in production.', null=True, verbose_name='Refresh Token')),
                ('token_expiry', models.DateTimeField(blank=True, help_text='Timestamp when the current access token expires.', null=True, verbose_name='Token Expiry')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the provider has verified this email address.', verbose_name='Verified Email')),
                ('last_login_at', models.DateTimeField(blank=True, help_text='Timestamp of the most recent successful login via this provider.', null=True, verbose_name='Last Login')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this social account link was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated At')),
                ('user', models.ForeignKey(help_text='The local user account this social login is linked to.', on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Social Account',
                'verbose_name_plural': 'Social Accounts',
                'db_table': 'social_auth_account',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'user'], name='idx_social_auth_provider_user'), models.Index(fields=['email'], name='idx_social_auth_email'), models.Index(fields=['last_login_at'], name='idx_social_auth_last_login')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_user_id'), name='uq_social_auth_provider_identity', violation_error_message='This social account is already linked to another user.'), models.UniqueConstraint(fields=('provider', 'user'), name='uq_social_auth_one_per_provider_per_user', violation_error_message='You have already linked this provider.')],
            },
        ),
    ]
