# Generated by Django 5.2.15 on 2026-07-19
"""
Convert ``SocialAccount.user`` from a single-model ``ForeignKey``
(``settings.AUTH_USER_MODEL`` = AdminUser) to a polymorphic
``GenericForeignKey`` via ``content_type`` + ``object_id`` +
``user_domain``.

This allows ``SocialAccount`` to link to *any* user model
(AdminUser, ITUser, ProfessorUser, CollegeUser, FacultyUser)
instead of being restricted to AdminUser only.

Steps
-----
1. Remove the old ``uq_social_auth_one_per_provider_per_user`` constraint
   (references the old ``user`` FK).
2. Remove the old ``idx_social_auth_provider_user`` index
   (references the old ``user`` FK).
3. Add ``content_type``, ``object_id``, ``user_domain`` columns
   (nullable initially — will be backfilled in step 4).
4. Backfill existing rows: all current records reference AdminUser via the
   ``user_id`` column, so we set content_type = AdminUser CT,
   object_id = user_id, user_domain = "admin".
5. Remove the old ``user`` FK column (drops ``user_id`` column too).
6. Add the new ``uq_social_auth_provider_user`` constraint
   (on provider + content_type + object_id).
7. Add the new ``idx_social_auth_provider_user`` index
   (on provider + content_type + object_id).
8. Make ``content_type``, ``object_id``, ``user_domain`` non-nullable.
"""

import uuid

import django.db.models.deletion
from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.db import migrations, models


# ---------------------------------------------------------------------------
# Data migration — backfill existing records
# ---------------------------------------------------------------------------


def backfill_user_references(apps, schema_editor):
    """Backfill existing SocialAccount rows from the old ``user_id`` FK.

    All existing records point to AdminUser, so we use the AdminUser
    ContentType and the domain ``"admin"``.
    """
    SocialAccount = apps.get_model("social_auth", "SocialAccount")
    ContentTypeModel = apps.get_model("contenttypes", "ContentType")

    admin_ct = ContentTypeModel.objects.get_for_model(
        apps.get_model(settings.AUTH_USER_MODEL)
    )

    for account in SocialAccount.objects.all():
        # read the old FK value that still lives in the column
        user_id = account.user_id  # still accessible before RemoveField
        if user_id:
            account.content_type = admin_ct
            account.object_id = user_id
            account.user_domain = "admin"
            account.save(update_fields=["content_type", "object_id", "user_domain"])


def reverse_backfill(apps, schema_editor):
    """Reverse is a no-op — data is preserved in the old FK if rolled back."""
    pass


# ---------------------------------------------------------------------------
# Migration
# ---------------------------------------------------------------------------


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("social_auth", "0001_initial"),
    ]

    operations = [
        # 1. Remove old constraint that references ``user`` FK
        migrations.RemoveConstraint(
            model_name="socialaccount",
            name="uq_social_auth_one_per_provider_per_user",
        ),
        # 2. Remove old index that references ``user`` FK
        migrations.RemoveIndex(
            model_name="socialaccount",
            name="idx_social_auth_provider_user",
        ),
        # 3. Add new polymorphic FK fields (nullable for backfill)
        migrations.AddField(
            model_name="socialaccount",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.ContentType",
                verbose_name="User Type",
                help_text="The model class of the linked local user (AdminUser, ITUser, etc.).",
                null=True,  # temporary for backfill
            ),
        ),
        migrations.AddField(
            model_name="socialaccount",
            name="object_id",
            field=models.UUIDField(
                db_index=True,
                verbose_name="User ID",
                help_text="UUID of the linked local user.",
                null=True,  # temporary for backfill
            ),
        ),
        migrations.AddField(
            model_name="socialaccount",
            name="user_domain",
            field=models.CharField(
                max_length=20,
                choices=[
                    ("admin", "Admin"),
                    ("it", "IT"),
                    ("professor", "Professor"),
                    ("college", "College"),
                    ("faculty", "Faculty"),
                ],
                db_index=True,
                verbose_name="User Domain",
                help_text="Domain of the linked user (admin, it, professor, college, faculty).",
                null=True,  # temporary for backfill
            ),
        ),
        # 4. Backfill existing data from old ``user_id`` FK
        migrations.RunPython(
            backfill_user_references,
            reverse_code=reverse_backfill,
        ),
        # 5. Remove old ``user`` FK (drops the old ``user_id`` column)
        migrations.RemoveField(
            model_name="socialaccount",
            name="user",
        ),
        # 6. Add new constraint (provider + content_type + object_id)
        migrations.AddConstraint(
            model_name="socialaccount",
            constraint=models.UniqueConstraint(
                fields=["provider", "content_type", "object_id"],
                name="uq_social_auth_provider_user",
                violation_error_message="You have already linked this provider.",
            ),
        ),
        # 7. Add new index (provider + content_type + object_id)
        migrations.AddIndex(
            model_name="socialaccount",
            index=models.Index(
                fields=["provider", "content_type", "object_id"],
                name="idx_social_auth_provider_user",
            ),
        ),
        # 8. Make new fields non-nullable (after backfill)
        migrations.AlterField(
            model_name="socialaccount",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.ContentType",
                verbose_name="User Type",
                help_text="The model class of the linked local user (AdminUser, ITUser, etc.).",
            ),
        ),
        migrations.AlterField(
            model_name="socialaccount",
            name="object_id",
            field=models.UUIDField(
                db_index=True,
                verbose_name="User ID",
                help_text="UUID of the linked local user.",
            ),
        ),
        migrations.AlterField(
            model_name="socialaccount",
            name="user_domain",
            field=models.CharField(
                max_length=20,
                choices=[
                    ("admin", "Admin"),
                    ("it", "IT"),
                    ("professor", "Professor"),
                    ("college", "College"),
                    ("faculty", "Faculty"),
                ],
                db_index=True,
                verbose_name="User Domain",
                help_text="Domain of the linked user (admin, it, professor, college, faculty).",
            ),
        ),
    ]
