from django.urls import path

from apps.applications.api.v1.views_it import (
    ApplicationStatisticsView,
    CompanyJobApplicationListView,
    JobApplicationCertificateDownloadView,
    JobApplicationCertificatePreviewView,
    JobApplicationCertificatesView,
    JobApplicationDetailView,
    JobApplicationInterviewDetailView,
    JobApplicationInterviewListCreateView,
    JobApplicationListCreateView,
    JobApplicationNotesView,
    JobApplicationResumeDownloadView,
    JobApplicationStatusHistoryView,
    JobApplicationStatusView,
    JobApplicationTimelineView,
    JobApplicationWithdrawView,
    RecruiterJobApplicationListView,
)

urlpatterns = [
    path("", JobApplicationListCreateView.as_view(), name="job-applications"),
    path(
        "recruiter/",
        RecruiterJobApplicationListView.as_view(),
        name="recruiter-job-applications",
    ),
    path(
        "statistics/",
        ApplicationStatisticsView.as_view(),
        name="job-application-statistics",
    ),
    path(
        "company/<uuid:company_id>/",
        CompanyJobApplicationListView.as_view(),
        name="company-job-applications",
    ),
    path(
        "<uuid:application_id>/",
        JobApplicationDetailView.as_view(),
        name="job-application-detail",
    ),
    path(
        "<uuid:application_id>/status/",
        JobApplicationStatusView.as_view(),
        name="job-application-status",
    ),
    path(
        "<uuid:application_id>/withdraw/",
        JobApplicationWithdrawView.as_view(),
        name="job-application-withdraw",
    ),
    path(
        "<uuid:application_id>/notes/",
        JobApplicationNotesView.as_view(),
        name="job-application-notes",
    ),
    path(
        "<uuid:application_id>/history/",
        JobApplicationStatusHistoryView.as_view(),
        name="job-application-history",
    ),
    path(
        "<uuid:application_id>/timeline/",
        JobApplicationTimelineView.as_view(),
        name="job-application-timeline",
    ),
    path(
        "<uuid:application_id>/resume/download/",
        JobApplicationResumeDownloadView.as_view(),
        name="job-application-resume-download",
    ),
    path(
        "<uuid:application_id>/certificates/",
        JobApplicationCertificatesView.as_view(),
        name="job-application-certificates",
    ),
    path(
        "<uuid:application_id>/certificates/<uuid:certification_id>/download/",
        JobApplicationCertificateDownloadView.as_view(),
        name="job-application-certificate-download",
    ),
    path(
        "<uuid:application_id>/certificates/<uuid:certification_id>/preview/",
        JobApplicationCertificatePreviewView.as_view(),
        name="job-application-certificate-preview",
    ),
    path(
        "<uuid:application_id>/interviews/",
        JobApplicationInterviewListCreateView.as_view(),
        name="job-application-interviews",
    ),
    path(
        "<uuid:application_id>/interviews/<uuid:interview_id>/",
        JobApplicationInterviewDetailView.as_view(),
        name="job-application-interview-detail",
    ),
]
