# Generated by Django 5.2.15 on 2026-07-02 19:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuthToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("domain", models.CharField(db_index=True, max_length=20)),
                ("user_id", models.UUIDField(db_index=True)),
                ("email", models.EmailField(max_length=254)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("password_reset", "Password Reset"),
                            ("email_verification", "Email Verification"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "auth_token",
                "indexes": [
                    models.Index(
                        fields=["domain", "user_id", "purpose"],
                        name="auth_token_domain_fdd843_idx",
                    )
                ],
            },
        ),
    ]
