# Generated by Django 5.2.15 on 2026-07-03 15:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_auth_security_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionRevocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(db_index=True, max_length=20)),
                ("user_id", models.UUIDField(db_index=True)),
                ("revoked_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("revoked_by_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "auth_session_revocation",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("domain", "user_id"),
                        name="uniq_session_revocation_domain_user",
                    )
                ],
            },
        ),
    ]
