# Generated by Django 5.2.15 on 2026-07-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0005_user_login_session_uuid"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="securityauditevent",
            new_name="auth_securi_domain_e7b9fc_idx",
            old_name="auth_audit_user_idx",
        ),
        migrations.RenameIndex(
            model_name="userloginsession",
            new_name="auth_user_l_domain_3584ef_idx",
            old_name="auth_session_user_idx",
        ),
        migrations.AlterField(
            model_name="connectedoauthaccount",
            name="created_by_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="userloginsession",
            name="created_by_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
