# Generated by Django 5.2.15 on 2026-07-02 19:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("recipient_domain", models.CharField(db_index=True, max_length=20)),
                ("recipient_id", models.UUIDField(db_index=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[("in_app", "In App"), ("email", "Email")],
                        default="in_app",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("body", models.TextField(blank=True)),
                ("event_type", models.CharField(db_index=True, max_length=100)),
                ("entity_type", models.CharField(blank=True, max_length=50)),
                ("entity_id", models.UUIDField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "notification",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient_domain", "recipient_id", "-created_at"],
                        name="notif_recipient_idx",
                    )
                ],
            },
        ),
    ]
